### ISSUE TITLE
QA: Trail Access/Display

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#100]
- [x] Display trail access only if there is an “atype=trailhead” entry in activities table associated with that POI
- [x] Display only one trail system (dictated by trail_info_id)
- [x] Display only one trail segment (dictated by trail_info_id) above the “with access to” 
- [x] Always display at least one segment (even if under 1 mile). Examples: Kickapoo Woods, Dan Ryan Woods
- [ ] If a trailhead has an aname, use that in place of the auto naming

**Comment by shua123** [comment]
We were already always displaying at least one segment for entrance/poi detail panel. I've fixed it to now display the first segment no matter the length for trail subsystem detail panels too.

**Comment by shua123** [comment]
@versatilehuman  for the Trailhead naming, what do you mean by in place of auto naming? 

Generally we are now using the nameid field where it exists to join with the names table to get names.

**Comment by shua123** [comment]
> Display trail access only if there is an “atype=trailhead” entry in activities table associated with that POI

Added with Trailsyserver commit https://github.com/smartchicago/trailsyserver/commit/c9ecaa1341411a78e9df562b13d3574752e9600f

**Comment by shua123** [comment]
@versatilehuman I am still a little unclear on the expectations for trailhead naming.

For activities in general, the name is populated by:
1. names.name based on activities.nameid=names.nameid
2. If (1) produces nothing, fall back to activities.aname for name.

Trailheads are similarly done as:
1. names.name based on activities.nameid=names.nameid + " Trail Access"
2. If (1) produces nothing, fall back to activities.aname for name  + " Trail Access"

So is the idea to get rid of the " Trail Access" part and rely on names.name and activities.aname only?

**Comment by versatilehuman** [comment]
I talked to Garret and he wants to keep the names.nameid first approach. So I need to go back and add new nameids for many of the new activities and update the name table (I had never seen the name table and clearly didn't understand the naming approach). Addressing it that way, I can add "Future Access" on the data side and make sure new activities are named correctly.

**Comment by versatilehuman** [comment]
@shua123 We lost Trail Access in the panel.

**Comment by versatilehuman** [comment]
Any lingering issues covered by #125
