### ISSUE TITLE
Styling for Unbuilt trails

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#101]
> Part of the North Branch and Cal Sag Trails will be given a trail_color=future extension. This should be rendered as grey.

**Comment by shua123** [comment]
This has been updated. I am going to leave this open until there is real data to test against.

**Comment by shua123** [comment]
This should be working. The only segment with a future tag right now is a small segment of Cal-Sag Trail.

**Comment by versatilehuman** [comment]
Ryan needs to update CSS.
