### ISSUE TITLE
QA: More Detail panel updates

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#102]
- [x] Under 1 mile: Add: `<span class="fpccOneMile">*Segments under 1 mile not shown.</span>`
After the last fpccTrailSegment div on both POI trail access and Trail System panels. (Styled in new CSS file)
- [x] Move “More Information” section- Move fpccLinks div below the fpccHours div and replace:
`<div class="fpccMoreHeader"><span class="fpccMoreName">More Information</span></div>`
with: `<span class="fpccLabel">More Information</span>`

**“More Information” additions**
- [x] In poi_info, IF picnic_grove=1 OR shelter=1
Include this in list:
`<a target="_blank" href="http://fpdcc.com/permits/">Picnic &amp; Event Permits</a>`
- [x] In poi_info, IF boat_ramp=1 OR canoe=1 OR boat_rental=1
Include this in list:
`<a target="_blank" href="http://fpdcc.com/boating/">Boating Information</a>`
- [x] In poi_info, IF fishing=1
Include this in list:
`<a target="_blank" href="http://fpdcc.com/fishing/">Fishing Information</a>`
- [x] Include in all POIs:
`<a target="_blank" href="http://fpdcc.com/rules-and-regulations/">Rules &amp; Regulations</a>`

**Nature Preserves info**
- [x] In poi_info, IF nature_preserve=1
Include this after fpccAmenities div:
`<div class="fpccNP clearfix" target="_blank"><a href="http://fpdcc.com/illinois-nature-preserves/" target="_blank"><img src="http://fpdcc.com/wp-content/uploads/2016/07/idnr-np-logo.png" width="75" height="65" alt="Illinois Nature Preserves Commission Logo"></a><p>This is an Illinois Nature Preserve&mdash;one of the highest quality natural lands in the state. This designation includes increased levels of legal protection and management. <a href="http://fpdcc.com/illinois-nature-preserves/" target="_blank">Learn more &gt;</a></p></div>`

**Comment by versatilehuman** [comment]
My bad--missed class="fpccMore" to make these show up green. 

Can the new links be added to the end instead of beginning of list since they are less specific to the location?

![image](https://cloud.githubusercontent.com/assets/7032169/17300192/f4c1b6a4-57d6-11e6-8043-02b6971cb1b9.png)

**Comment by versatilehuman** [comment]
Closing -- have a note to check Nature Preserves after data update.

**Comment by versatilehuman** [comment]
@shua123 Not seeing Nature Preserve info after data update. Not in data?

In poi_info, IF nature_preserve=1 Include this after fpccAmenities div: <div class="fpccNP clearfix" target="_blank"><a href="http://fpdcc.com/illinois-nature-preserves/" target="_blank"><img src="http://fpdcc.com/wp-content/uploads/2016/07/idnr-np-logo.png" width="75" height="65" alt="Illinois Nature Preserves Commission Logo"></a><p>This is an Illinois Nature Preserve&mdash;one of the highest quality natural lands in the state. This designation includes increased levels of legal protection and management. <a href="http://fpdcc.com/illinois-nature-preserves/" target="_blank">Learn more &gt;</a></p></div>

**Comment by shua123** [comment]
Nature Preserve field added back in on server(https://github.com/smartchicago/trailsyserver/commit/64c616bbc2f6803db61ee9a3aaf457c402841446) so message should show now.

**Comment by versatilehuman** [comment]
Looks good.

**Comment by versatilehuman** [comment]
@shua123 Can we make this change to the "More Information" links:

Spanish Map (PDF) --> Mapa Español (PDF)

**Comment by versatilehuman** [comment]
Same here, cleared cache, still seeing:

![image](https://cloud.githubusercontent.com/assets/7032169/19198971/659b7484-8c87-11e6-9b81-090f57849b71.png)

**Comment by shua123** [comment]
Hmm, Its showing correctly for me and the code is correct (https://github.com/smartchicago/trailsy/blob/gh-pages/js/trailhead.js#L2522). Try clearing cache again. Maybe gh-pages didn't build correctly one time.

**Comment by versatilehuman** [comment]
Looks good now.
