### ISSUE TITLE
Tower Road Canoe/Kayak Rental title showing up on map

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#105]
![image](https://cloud.githubusercontent.com/assets/7032169/17409665/cd0da9e0-5a35-11e6-981c-dd0c685c16b6.png)

**Comment by shua123** [comment]
Are there are any activities that you want names on the map for now?

**Comment by versatilehuman** [comment]
No, I think the long term goal is to have a basemap with some helpful labels for rec waterbodies and larger preserves. Rendering the name adds to the clutter and I'm not sure it adds a lot that we couldn't accomplish more elegantly with the basemap.
