### ISSUE TITLE
Sign icon size during search

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#106]
Certain searches with a small number of results spread out across the county that return trails and POIs make it really difficult to locate the search results on the map. 

Example: http://fpcc-staging.smartchicagoapps.org/#/?search=camping

![image](https://cloud.githubusercontent.com/assets/7032169/17444990/6ae17386-5b08-11e6-8859-706eb1079485.png)

@shua123 Any ideas? 
- Make the initial scale of the sign icons larger -- looks more cluttered on first load, but helps with this issue. Not sure that initial screen is useful without a zoom or search anyway, so might be the easiest, least disruptive solution.
- Tie sign icon size to number of points on the map/zoom level -- not sure how feasible this is.
- Display all trails as a single neutral color at initial zoom and maybe a few zoom levels in? Maybe in combination with first or second idea?

**Comment by shua123** [comment]
In v2 I am trying marker clustering for POI signs. At a larger zoom level we can set the cluster icon to be larger.

**Comment by versatilehuman** [comment]
Test mobile clickabilty at different sizes/levels

**Comment by versatilehuman** [comment]
This is fine for now, adding to future enhancements (#160)
