### ISSUE TITLE
Change select(ize) menu to open up when search contracted

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#112]

**Comment by versatilehuman** [comment]
& fix border issue.

**Comment by versatilehuman** [comment]
@shua123 Looks like the styling determining position is inline. When contracted (map view) need to remove "top" property (or set to auto) and set "bottom:0." Height could be an issue, need to test on actual devices.

![image](https://cloud.githubusercontent.com/assets/7032169/19663127/3b156ac2-9a00-11e6-821e-b92d4da7c51b.png)

**Comment by shua123** [comment]
I'm using a version of the selectize code that merges in one of the auto direction pull requests in the selectize repo by ftalves https://github.com/smartchicago/trailsy/commit/d7a0b1786d5d92d2e661c3caae300327878b2ba6

**Comment by versatilehuman** [comment]
getting a gap/hiding list:
![screenshot_2017-02-15-10-31-39](https://cloud.githubusercontent.com/assets/7032169/22985660/a781800c-f36e-11e6-91c3-889e81b85457.png)

**Comment by versatilehuman** [comment]
Assuming related to change, popular list is under "everything" now:

![image](https://cloud.githubusercontent.com/assets/7032169/22985723/e1a6650e-f36e-11e6-9038-76a3e8505b72.png)

**Comment by versatilehuman** [comment]
Should be:

Popular
-A
-D
-F

Everything:
-A
-B
-C
-D
-E
-F

**Comment by shua123** [comment]
Gap fixed through updating selectize: https://github.com/shua123/selectize.js/commit/433d7e3418f980b43a682b5a8c4313015252dfa7

**Comment by shua123** [comment]
The Popular/Everything issue is that it does not like having the same option appear in a list twice. The easiest would be to not have Popular stuff in Everything also. Alternatively I guess the hacky solution would be to give the popular options a slightly different value (like "hiking-popular" vs "hiking") and then filter out the "-popular" part when the javascript reads it.

**Comment by versatilehuman** [comment]
@shua123 Can we do the hack for now and then see how many people are selecting the "popular" items from the "everything" menu?

**Comment by shua123** [comment]
I've added "-popular" to the value of the popular options https://github.com/smartchicago/trailsy/commit/1bf4b84fde7ba08c58abc2d7c2d12afee753dbd9

I'll might make GA events for the select selection to track it

**Comment by versatilehuman** [comment]
@shua123 Hiking was in the "everything" twice -- I removed on GH pages.

**Comment by versatilehuman** [comment]
Closing here, but iOS issue documented in #120
