### ISSUE TITLE
Add bathroom locations / seasonality

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#113]
Create data sets for:
- permanent bathrooms 
  -- location
  -- seasonality
  -temporary bathrooms
  -- location (if possible)
  -- seasonality

**Comment by versatilehuman** [comment]
Working with Garret to add this information to the panel, but not on map. (Almost) all bathrooms are right off the parking lot, so we'd add a lot of clutter (especially preserves with multiples) and need to load all those extra icons.

**Comment by shua123** [comment]
Bathroom info added to the detail panel. We need to fix the styling of the disclaimers

**Comment by versatilehuman** [comment]
@shua123 Yeah, that wasn't going well for me editing the bundle.js so I could see the changes. 

I'll add the CSS, can you update to this:

```
<div class="bathroom-season">*Indoor bathroom...</div>

<div class="portable-bathroom-season">**Portable bathroom...</div>

```
And can you switch the asterisks to proceed the labels:

*Indoor Bathroom
**Portable Bathroom

I'm getting the label showing up on three lines for "Accessible Portable Bathroom**"

**Comment by versatilehuman** [comment]
- Fix bathroom SVGs
- Little Red & Sagawau missing bathrooms

**Comment by shua123** [comment]
Disclaimer divs added: https://github.com/smartchicago/trailsy/commit/5abf92b4db3c988ef77a3868a634d11cc502ac39
Asterisks moved: https://github.com/smartchicago/trailsy/commit/d1ad778fe0e73ddbedc73fba0741cff710d3c49a
