### ISSUE TITLE
John Husar I&M Canal Trail not rendering

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#117]
Likely due to lack of trailhead. Will get one in the new data and see what happens.

![image](https://cloud.githubusercontent.com/assets/7032169/18764774/928bc54e-80d8-11e6-9190-63757f4715c6.png)

![image](https://cloud.githubusercontent.com/assets/7032169/18764831/c15e5f62-80d8-11e6-9fdb-002517cf276b.png)

**Comment by versatilehuman** [comment]
Also check John Husar I&M Canal Trail after data update. Not rendering:
http://smartchicago.github.io/trailsy/#/?trail=John+Husar+I%26M+Canal+Trail

![image](https://cloud.githubusercontent.com/assets/7032169/19653797/7a1dd940-99db-11e6-8476-8aa49380f197.png)

**Comment by shua123** [comment]
Horizon Farm Trail shows with latest data update thanks to new trailhead.

**Comment by shua123** [comment]
I'm not sure what is going on with Husar trail.

**Comment by versatilehuman** [comment]
@shua123 Still not rendering with latest updates.

**Comment by versatilehuman** [comment]
@shua123 Maybe it's the &? Need to format as `&amp;`?

**Comment by shua123** [comment]
Fixed https://github.com/smartchicago/trailsy/commit/d5440455104144b0a6bab1c598ea308f776bf842
