### ISSUE TITLE
Amend toggle functionality

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#118]
- Toggle only switches by direct touch
- “Back to..." determined by previous page (list or map)

**Comment by shua123** [comment]
@versatilehuman please have a look at the current gh-pages version of this.

**Comment by versatilehuman** [comment]
Looking good. Thoughts: 

When toggle is on list, this should read, "< Back to List" 
![image](https://cloud.githubusercontent.com/assets/7032169/19080652/56ecc8aa-8a1d-11e6-941d-70b2780c1f5b.png)

When panel is expanded from map:
![image](https://cloud.githubusercontent.com/assets/7032169/19080792/d1ef883a-8a1d-11e6-8364-b56472720492.png)

Then user toggles to list, language should switch to "< Back to List" -- currently stays "< Back to Map" (but does navigate back to list)
![image](https://cloud.githubusercontent.com/assets/7032169/19080838/f92a2004-8a1d-11e6-859a-e55c73049a95.png)

**Comment by shua123** [comment]
Changes made on gh-pages

**Comment by versatilehuman** [comment]
Looks good.
