### ISSUE TITLE
Loading animation

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#119]
Eliminate flash of partially styled content and implement loading animation

**Comment by versatilehuman** [comment]
@shua123 Both my phones are hanging up w/ loading animation on initial load to list view. The page itself is loaded, but animation keeps spinning and you never get to the list. If I switch to map view I can navigate around and select locations, but I can never see the actual list. 

Map is painfully slow (a few seconds delay on pinch-zoom). Hoping this is loading animation related. Are you seeing similar issues?

**Comment by versatilehuman** [comment]
@shua123 Or maybe the map is the issue, taking too long to load in the background? Once I switch to the map and it is fully loaded, I can get back to the list. But sometimes that takes several minutes.

**Comment by shua123** [comment]
My phone is having issues with map slowness. I haven't had your animation/list issues.
What are the phone+browsers?

**Comment by shua123** [comment]
On the map side, I think part of it is that we have too many things actively displaying. I am messing with a test version at https://fpcc-staging.smartchicagoapps.org/index-testing.html without trail segments and that loaded a little better. Also, when I search/filter the map it performs much better with fewer pois displaying. We may have to make different display decisions for mobile.

I'm concerned about the list hanging you are experiencing @versatilehuman on load though. Test out the testing page and filtering.

**Comment by versatilehuman** [comment]
Map definitely moves better after search. Will need to think about what to load when.

Hanging up:
iPhone 4s w/ iOS 9.3.5 on Safari
Moto G w/ Android 5.1 on Firefox 49.0.2

Loads list:
Moto G w/ Android 5.1 on Chrome 54.0.2840.85

Once I switch to map after the hang up, I get this on both phones:
![img_1614](https://cloud.githubusercontent.com/assets/7032169/20435638/74cd8288-ad72-11e6-926b-1005316b38a0.PNG)

**Comment by shua123** [comment]
Lets move discussion about mobile and browser issues to #120

**Comment by versatilehuman** [comment]
moved to #120

**Comment by versatilehuman** [comment]
way to hide stuff loading in background. Message to acknowledge loading time.

**Comment by versatilehuman** [comment]
mess with timout settings, etc.

**Comment by versatilehuman** [comment]
Not sure if these are feasible.

How about:

loading map...

![image](https://cloud.githubusercontent.com/assets/7032169/23084729/77e598d0-f529-11e6-8241-a17aadd35a86.png)

After 3-4 seconds?

still loading...

![image](https://cloud.githubusercontent.com/assets/7032169/23084830/f368d210-f529-11e6-943a-20c479e7156b.png)


OR

Percentage loader?

![image](https://cloud.githubusercontent.com/assets/7032169/23084982/ac96394e-f52a-11e6-81dd-1e6386650c74.png)

**Comment by versatilehuman** [comment]
@shua123 Looks like new update added my changes.
