### ISSUE TITLE
Add location finder to mobile

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#122]

**Comment by versatilehuman** [comment]
@shua123 CSS should be good for this, but it has a "display:none" inline style on mobile.

**Comment by shua123** [comment]
@versatilehuman It should be showing on the map right now if you have share location enabled. Is it not for you?

**Comment by versatilehuman** [comment]
@shua123 Having trouble fully loading on either phone right now. I'll check again later.

**Comment by versatilehuman** [comment]
@shua123 Can't see it on the map regardless of location on both devices, not sure if issues I mentioned in #119  are related.

**Comment by versatilehuman** [comment]
Looks good.
