### ISSUE TITLE
Use SVG lines in panel to better match map trail paths

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#127]
@shua123 Thoughts? I replaced the css borders we were using in the panel to better match look of the trail paths on the map. They are now all SVG. I positioned them so dotted/dashed lines were optimized for the desktop panel width (on mobile the varied width means they may stop short or get cut off on the right side). 

desktop:
![image](https://cloud.githubusercontent.com/assets/7032169/19288745/1b06afc6-8fcd-11e6-84ec-f95f3023b83c.png)

mobile:
![image](https://cloud.githubusercontent.com/assets/7032169/19288844/9fe70f9c-8fcd-11e6-9fc9-68e9cacac080.png)

trailhead.js:
https://github.com/smartchicago/trailsy/blob/gh-pages/js/trailhead.js#L2683

CSS:
https://github.com/smartchicago/trailsy/blob/gh-pages/styles/css/newguts.css#L186

**Comment by shua123** [comment]
Looks good
