### ISSUE TITLE
Label spurs & loops to prevent adding mileage 

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#128]
Adding a column for Trail/Loop/Spur and directional North/South/East/West to differentiate between duplicate colors.

Getting Garret a list for future data update:

![image](https://cloud.githubusercontent.com/assets/7032169/19356992/48d411d2-9135-11e6-96ac-015d7259d3f2.png)

**Comment by versatilehuman** [comment]
Sent to Garret today.

**Comment by shua123** [comment]
I did not see this in the most recent data from Garret

**Comment by versatilehuman** [comment]
Garret is working on adding all Trail Systems with this issue. Last update just had Busse.

**Comment by versatilehuman** [comment]
@shua123 Will give guidance on updating naming once we have the data.

**Comment by shua123** [comment]
Naming formatting: https://github.com/smartchicago/trailsy/issues/107#issuecomment-278093424

**Comment by versatilehuman** [comment]
Closing for now, will QA.
