### ISSUE TITLE
Panel height resize off 

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#129]
From home: clicking on a POI in the list: 

The panel isn't rezsizing:
![image](https://cloud.githubusercontent.com/assets/7032169/19395214/203680de-9202-11e6-9b54-2b3260c6bdf8.png)

Not sure if updates we've made have impacted this.

**Comment by shua123** [comment]
Should be fixed.

**Comment by versatilehuman** [comment]
Looks good.
