### ISSUE TITLE
Better differentiate between off-FPDCC trails

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#130]
@shua123 Take a look at panel/map strokes. I basically used a muted version of the trail color so all off-fpdcc weren't gray. Example: http://smartchicago.github.io/trailsy/#/?trail=Thorn+Creek+Trail+System

Can you double check these last two commits to make sure I did this properly:
https://github.com/smartchicago/trailsy/commits/gh-pages/js/trailhead.js

**Comment by shua123** [comment]
I think that looks okay.
