### ISSUE TITLE
Link pop-up POI and Trail names on mobile

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#132]
My concern is that people will click on a point and not notice the subtle change in the green bar at bottom, so this would be another avenue to reach the panel info. Examples: 

Clicking on "Beck Lake" in popup would slide the panel up for Beck Lake. Clicking on "Des Plaines Trail System" would slide up the panel for Des Plaines Trail System:

![image](https://cloud.githubusercontent.com/assets/7032169/21442003/dd82a430-c860-11e6-9c27-58db3cabf2e0.png)

Clicking on "Des Plaines Trail System" would slide up the panel for Des Plaines Trail System:

![image](https://cloud.githubusercontent.com/assets/7032169/21442045/1104ce0a-c861-11e6-87e8-37b90d8713cf.png)

**Comment by shua123** [comment]
This is implemented in v2

**Comment by versatilehuman** [comment]
@shua123 Added styling for this. Mobile with show linked text in pop-up to indicate link.

**Comment by versatilehuman** [comment]
I need to update a few things here.

**Comment by versatilehuman** [comment]
Moving from minor testing issues:

@shua123 svg right arrow missing here, drop after highlighted code:
![screen shot 2017-02-25 at 6 36 39 pm](https://cloud.githubusercontent.com/assets/7032169/23336074/88ce77d2-fb89-11e6-9e6f-c5f4008bdfc3.png)

**Comment by shua123** [comment]
Added with https://github.com/smartchicago/trailsy/commit/1e8cfc7d4f597e120c70170607c15d541f7f6877. It is positioned correctly in the html but the arrow is appearing next to the segment name (Red Paved) instead of next to system.

**Comment by versatilehuman** [comment]
Couldn't fix it with CSS, no idea what's happening. If you put it before the highlighted code it seems to work.

**Comment by shua123** [comment]
Okay, I moved it up https://github.com/smartchicago/trailsy/commit/8c15ed7bec5a79316f1ae370c354e76000adbf97
