### ISSUE TITLE
Street/Satellite toggle behavior

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#133]
Showing up as a blank box sometimes (almost always after interacting with it):

![image](https://cloud.githubusercontent.com/assets/7032169/22380580/907a3920-e483-11e6-8038-b9f21bf82355.png)

**Comment by shua123** [comment]
I think this issue is fixed in the new version

**Comment by versatilehuman** [comment]
newguts.css line 462 display:none

**Comment by shua123** [comment]
Fix to show toggle control on mobile: https://github.com/smartchicago/trailsy/commit/a43c78ecaae5e34cfb711042b854949c0fb81fbe
