### ISSUE TITLE
Mobile search map zoom level

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#135]
To enhance performance we were experimenting with only loading the area directly around the user's location. 

It's impacting search zoom level. This search for camping, with five results, is zoomed tightly around the first result only, instead of showing all five:

![image](https://cloud.githubusercontent.com/assets/7032169/22380824/9641893e-e484-11e6-8d15-b811747f4c0a.png)

**Comment by shua123** [comment]
In branch v2, I am no longer zooming into first search result
