### ISSUE TITLE
Pop-up not displaying when trail selected from panel list

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#139]
When clicking directly on trail, you get pop-up:

![image](https://cloud.githubusercontent.com/assets/7032169/22443573/f4b7c190-e704-11e6-966e-0dfcedf55a13.png)

When you select from list, you don't:

![image](https://cloud.githubusercontent.com/assets/7032169/22443607/15a5a610-e705-11e6-9f44-40c310378462.png)

Pop-up displays for POIs in both instances.

**Comment by shua123** [comment]
This is a bit complicated. It might look okay in a situation like Miller Meadow but for bigger trail subsystems the map will be zoomed out more and the popup might look weird. We also would have to figure out how to determine where the popup should open on the map.

**Comment by versatilehuman** [comment]
Got it. Bad example. Miller Meadow and other non-linear systems zoom and I think that's sufficient. 

This is the scenario I'm most concerned about, when we have a linear trail selected from the panel. Some users may not be able to see that it's highlighted. Don't have any great ideas on addressing.

![image](https://cloud.githubusercontent.com/assets/7032169/22703781/f3bbfd5c-ed2a-11e6-93d8-112538c99681.png)
