### ISSUE TITLE
IE & no-script pop-up/language

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#140]

**Comment by versatilehuman** [comment]
@shua123 For IE:

`<div class="function-message-bg">
    <div class="function-message">
<h2>Please Upgrade Your Browser to Use This Website</h2>
<p>Microsoft no longer supports your version of Internet Explorer and this website will not function properly using this browser. You can:</p>
        <ul>
            <li>Upgrade to <a href="https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support" target="_blank">Internet Explorer 11</a> <em>(or <a href="https://www.microsoft.com/en-us/windows/microsoft-edge" target="_blank">Microsoft Edge</a> on Windows 10)</em>.</li>
            <li>Use a different browser <em>(like <a href="https://www.google.com/chrome/" target="_blank">Google Chrome</a> or <a href="https://www.mozilla.org/en-US/firefox/new/" target="_blank">Mozilla Firefox</a>)</em>.</li>
            <li><a href="http://fpdcc.com/preserves-and-trails/maps/" target="_blank">View PDF maps</a> of the Forest Preserves of Cook County</li>
        </ul>
    </div>
</div>`

For no-script:

`<div class="function-message-bg">
    <div class="function-message">
<h2>Please Enable Javascript to Use This Website</h2>
<p>This website use Javascript to function properly. You can:</p>
        <ul>
            <li><a href="http://enable-javascript.com/" target="_blank">Enable Javascript</a> and reload this page.</li>
            <li><a href="http://fpdcc.com/preserves-and-trails/maps/" target="_blank">View PDF maps</a> of the Forest Preserves of Cook County</li>
        </ul>
    </div>
</div>`

**Comment by shua123** [comment]
noscript added: https://github.com/smartchicago/trailsy/commit/57a818ace0b6ef3eaaa8aef109a4321baeac06ff
< IE 11 added: https://github.com/smartchicago/trailsy/commit/a2a7a4171b839b4ab4988b9bb0d316d40bee00c3
