### ISSUE TITLE
v2 issues

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#142]
@shua123 I know you still have some updates to bring it current, but wanted to document what I'm seeing (I'll add as a I see new stuff):

- [x] Muni & zip searches not reflected on map
- [x] Bike & equestrian parking showing up as sign icons (shouldn't be on map at all)
- [x] Activity icons showing up over sign icons
- [x] Activity icons no longer semi-transparent (before POI is selected)
- [x] After a search that yields 0 results, map doesn't reset when search is cleared
- [x] Recreation Center icon missing from map
- [x] Camping icon showing up as sign icon
- [x] When POI is selected from panel, sign icon is not highlighted on map
- [x] Satellite toggle gone
- [x] Kill blue hove polygon?
- [x] parking lot icon update (I want to test contrast on this, so I may update basemap and icon)
- [x] Entrances that share the same coordinates are being spaced diagonally instead of horizontally
- [x] Trail panel styling issue
- [x] No picnic shelters on map

Muni & zip searches not reflected on map
![image](https://cloud.githubusercontent.com/assets/7032169/22704336/f6d12970-ed2c-11e6-9511-c638d43d71f2.png)

Bike & equestrian parking showing up as sign icons (shouldn't be on map at all):
https://fpcc-staging.smartchicagoapps.org/v2/#/?poi=58-Camp+Kiwanis+Equestrian+Staging+Area
https://fpcc-staging.smartchicagoapps.org/v2/#/?poi=198-Poplar+Creek+Bicycle+Lot
https://fpcc-staging.smartchicagoapps.org/v2/#/?poi=331-Maple+Lake-East+-+Mountain+Bike+Staging+Area
https://fpcc-staging.smartchicagoapps.org/v2/#/?poi=347-Spring+Lake+Equestrian+Parking
![image](https://cloud.githubusercontent.com/assets/7032169/22704312/dcd5f67c-ed2c-11e6-97b0-6d4c1984ef08.png)

Activity icons showing up over sign icons:
![image](https://cloud.githubusercontent.com/assets/7032169/22704425/505b46a6-ed2d-11e6-8460-b9c6fdb4576e.png)

Activity icons no longer semi-transparent (before POI is selected)
![image](https://cloud.githubusercontent.com/assets/7032169/22704592/d61ff9da-ed2d-11e6-9173-0db03d61d5c4.png)

After a search that yields 0 results, map doesn't reset when search is cleared:
![image](https://cloud.githubusercontent.com/assets/7032169/22704538/aa493786-ed2d-11e6-872d-8129b1e25ba8.png)

Recreation Center icon missing (should be on map, waiting on data and it'll show up in panel too):
![image](https://cloud.githubusercontent.com/assets/7032169/22704635/009b803a-ed2e-11e6-88af-16c65b1f0666.png)

Camping icon showing up as sign icon:
![image](https://cloud.githubusercontent.com/assets/7032169/22704700/375cc19c-ed2e-11e6-9f83-3904185ac48c.png)

When POI is selected from panel, sign icon is not highlighted on map:
![image](https://cloud.githubusercontent.com/assets/7032169/22704736/6060068a-ed2e-11e6-9408-49862ebcfaeb.png)

Kill blue hove polygon?
![image](https://cloud.githubusercontent.com/assets/7032169/22704925/17620d10-ed2f-11e6-86e3-163ccdd992cf.png)

parking lot icon update:
![image](https://cloud.githubusercontent.com/assets/7032169/22704956/3932900e-ed2f-11e6-9d8f-021b0cf74a7c.png)

Entrances that share the same coordinates are being spaced diagonally instead of horizontally. Putting things deeper into the property or across the street from where they should be:
![image](https://cloud.githubusercontent.com/assets/7032169/22712244/c0ec6348-ed49-11e6-8365-7a417d462260.png)
![image](https://cloud.githubusercontent.com/assets/7032169/22712272/d62968fa-ed49-11e6-9ffc-0141e09d92d1.png)

**Comment by shua123** [comment]
- Muni/Zip search map pan/zoom: https://github.com/smartchicago/trailsy/commit/c75935065f423c8cd88ca8ffb376b5102faef77a
- Make activities below signs: https://github.com/smartchicago/trailsy/commit/5f9c6207ba6e7b8d8864fd00638b812e5f1f94c6
- Activity opacity https://github.com/smartchicago/trailsy/commit/ddb4a5a501289311e1a722159374c780058d1948
- Activity icon camp: https://github.com/smartchicago/trailsy/commit/820f94ffb02996457e5127be820f118016d802ed
- POI highlighting on selection: https://github.com/smartchicago/trailsy/commit/afa82897bdcc66617cef1d52d637d0d58035f54c
- No cluster hover blue boundary: https://github.com/smartchicago/trailsy/commit/2bc2c69d865bb9075bcae95fc7d88a8c7d5a9249
- better handling of 0 results https://github.com/smartchicago/trailsy/commit/17f3cc1442154b7752632e5ac7a595979378ee3f
- Don't include activities that do not have icons https://github.com/smartchicago/trailsy/commit/a91f5e920af76205cc8d0aa70419b1484c53a228
- Add back satellite toggle https://github.com/smartchicago/trailsy/commit/f658d550bc7ea31da77c211a4696cf7025166876

**Comment by versatilehuman** [comment]
Looks like some CSS didn't get transferred or got clipped? Or ID or class removed? Trying to check against GH pages version but it's not loading.

Left is Trail panel, right is Trail info in POI panel:

![image](https://cloud.githubusercontent.com/assets/7032169/22985515/46feefa8-f36e-11e6-8a05-42833e9e841d.png)

**Comment by versatilehuman** [comment]
No picnic shelter activity icons are showing up on map (all represented by picnic grove icon):

![image](https://cloud.githubusercontent.com/assets/7032169/22985921/9c846eac-f36f-11e6-9084-66e86c15d4b7.png)

**Comment by shua123** [comment]
PDF Trail Map text overlap issue: The issue is that POI detail panel info is not entirely within the fpccContainer div. Might be an extra close div or something in the js build code.

**Comment by shua123** [comment]
Picnic Grove shelters on map: https://github.com/smartchicago/trailsy/commit/dc185baf124eca2bc0823f1955d2cf8756f87bba
PDF Trail Map text overlap fix: https://github.com/smartchicago/trailsy/commit/766b9b61618acd845090b2bd391c42e3d82e35b3

**Comment by versatilehuman** [comment]
Contrast checker: http://webaim.org/resources/contrastchecker/

**Comment by versatilehuman** [comment]
@shua123 No picnic shelters issue is back:
![image](https://cloud.githubusercontent.com/assets/7032169/23467857/c049a74e-fe64-11e6-8bcd-5f2d3bbe3557.png)

**Comment by shua123** [comment]
We changed the field name for type so I had to update it. Done: https://github.com/smartchicago/trailsy/commit/45a27dceca51fcd71db3b448730c4a3d4c4e409c
