### ISSUE TITLE
Distance away is displayed even when location is not shared

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#146]
I noticed that even if I do not allow the website to use my location, the results still show a "# mi away." I expect that if I block my location that it would not have these associated distances. Another thought is that there would be a central part of the map marked and these distances would be relevant to that central map marker. 

This relates to issue #137.

**Comment by versatilehuman** [comment]
Good point. I think this was a legacy of early work where Beck Lake was the default and we didn't rethink this approach--just deciding to move it to a different arbitrary point (in Chicago).

If you didn't share location... that information isn't super useful, could be confusing and can border on creepy.

@shua123 Can we remove these if location is not shared? But add them back after a muni/ZIP search?

**Comment by shua123** [comment]
Done. If distances are being calculated by using distance from Config.mapCenter, distance won't display in list otherwise it will.

https://github.com/smartchicago/trailsy/commit/c2cf067339c79cdecd45520d78a1cc20b56eed9a

**Comment by versatilehuman** [comment]
Looks good. Would it be possible to do the list in alpha order? It looks like it's still ordered by distance from Chicago right now.

**Comment by shua123** [comment]
Yes, now implemented. Sorting by name alpha if there is no search/user location. https://github.com/smartchicago/trailsy/commit/2eb1ef29ba3f8d409ff489f62c1f79765e1f6740

**Comment by versatilehuman** [comment]
Trails are showing up out of order (following the first POI they are associated with). Not sure if there is a quick fix to this. If not, something we can address later:

![image](https://cloud.githubusercontent.com/assets/7032169/23183682/8ae2a786-f842-11e6-8dfa-b9a8473c6427.png)

**Comment by shua123** [comment]
Yeah, Trail divs in the list are entirely associated with the POI. Basic process:
1. Sort Filtered POIs by distance/alphabetical
2. Iterate through array of Filtered POIs.
     - Create poi div
    - Is there an associated Trail_Subsystem? Has a div been created? If no, create a trail subsystem div
