### ISSUE TITLE
After sharing location and searching, large section of map is still shown

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#147]
After I have allowed the site to know my location and after searching for "hiking/walking/running" I am curious as to why so much of the map is being shown. There are options very far from my current location. I am curious if the reason is to show the user all of their options versus only the options closest to them. 

In our previous CUTGroup test, 6 out of 17 testers prioritized distance when planning their trip to the Forest Preserves. My expectation would be to only see a smaller radius with one or two forest preserves that have the activity I am looking for.

Here is a screenshot of my search results:
<img width="1277" alt="screen shot 2017-02-16 at 9 08 07 pm" src="https://cloud.githubusercontent.com/assets/5550969/23051244/20dff14e-f48d-11e6-87cd-48a8eae98cee.png">

**Comment by versatilehuman** [comment]
Good question. As set up, it's simply filtering out locations that don't offer hiking--it doesn't consider location (except ordering the results in the panel on the left). 

I think I'd lean toward adding a filter feature that let's the user select the distance they are willing to travel rather than set that ourselves. 

For the hiking example, not all hiking is created equal. Your closest trail is paved and flat. But if you were looking for an unpaved trail with some elevation, you'd have to go to the southwest side of the county. If we filter that out, you might think that's not available.

If people are looking for a picnic grove, they may only want to see the closest ones--so that could work.

But if they were going camping, they may have a higher tolerance for traveling because they are staying overnight. We also wouldn't want to filter out campgrounds because they all offer different amenities. 

Would something like this better address this? 

![image](https://cloud.githubusercontent.com/assets/7032169/23071241/4176e42e-f4f3-11e6-9d4e-6dbb987a2510.png)

General filters:
- Location distance
- Parking availability

Dynamic filters (would show up only after a specific search):

IF trail related search:
- Trail Surface
- Trail Difficulty
- Accessibility
- Trail Length

IF camping:
- Campground types

IF picnic:
- Capacity

etc.

**Comment by shua123** [comment]
The advanced filtering is a good idea but I also like the idea of trying something different with the map fitbounds.

Right now we have the map fit the bounds of all results. To @smarziano comment 
> My expectation would be to only see a smaller radius with one or two forest preserves that have the activity I am looking for

We could just change what the fitbounds is doing. The list itself would be everything but the map would fitbounds to a smaller subset of the closest locations. Maybe not 1 or 2 but we could do closest 5 or 10 (possibly set this different for mobile vs desktop. Thoughts @versatilehuman ?

**Comment by versatilehuman** [comment]
I like that approach. Sorry, I was interpreting the comment as actually filtering points off the map. I think changing the fitbounds also helps now that we are clustering. For searches with a lot of results it's not clear that anything happened on the map.

Let's set it at 10 and see how that works, that will still show all the results for some of the more specialized searches (camping, nature centers, etc.) but focus for some of the broader searches (hiking, biking).

@shua123 Would this be 10 POIs or 10 POIs & trails?

**Comment by shua123** [comment]
The search fitbounds just looks at the array of matching POIs. 
Closest 10 is live: https://github.com/smartchicago/trailsy/commit/251c72fe0fd2d47a52e5213d551b5006d42f8aa7

**Comment by versatilehuman** [comment]
Couple comments:

- **Activity searches:** Looks good!
- **Initial load desktop:** I'm not sure about the "closest 10" view on initial load. Can we do full map for initial load? While some people are only going to be interested in their immediate area, we still want them to be aware that there are opportunities across the county--and don't want to limit other users. Depending on their location, they have some underwhelming options within an unfiltered "closest 10" (thinking about Family Picnic Areas along the Des Plaines). Even with full map view on initial load, their location is marked and the panel is ordered by closest preserve. Once they start searching, I think it makes sense to put them close to their location ("closest 10"). 
- **Initial load mobile:** Not sure about full map or closest 10 here. Have a feeling the majority of mobile users won't actually be in the preserves (though this will likely increase after launch). That said, on a smaller screen the closest 10 may be an easier place to start. Thoughts, @shua123? 
- **Zip/muni search:** Can we adjust for zip/muni searches to include the center point of the search? I believe in testing these searches were interpreted as a way for users to center themselves on the map, and some of these are giving less than desirable results:

60613:
![image](https://cloud.githubusercontent.com/assets/7032169/23176083/3872666e-f827-11e6-8578-c7856714cb04.png)

Chicago:
![image](https://cloud.githubusercontent.com/assets/7032169/23176096/497ceb6e-f827-11e6-90c7-4d2816eba2ad.png)

**Comment by shua123** [comment]
- **Initial load desktop:** I'm not sure about the "closest 10" view on initial load. Can we do full map for initial load? While some people are only going to be interested in their immediate area, we still want them to be aware that there are opportunities across the county--and don't want to limit other users. Depending on their location, they have some underwhelming options within an unfiltered "closest 10" (thinking about Family Picnic Areas along the Des Plaines). Even with full map view on initial load, their location is marked and the panel is ordered by closest preserve. Once they start searching, I think it makes sense to put them close to their location ("closest 10"). - _Okay I've changed this to load full on desktop for initial load_ https://github.com/smartchicago/trailsy/commit/d9a0b579782568b35e681b8415be8c4c52e364d1
- **Initial load mobile:** Not sure about full map or closest 10 here. Have a feeling the majority of mobile users won't actually be in the preserves (though this will likely increase after launch). That said, on a smaller screen the closest 10 may be an easier place to start. Thoughts, @shua123?  - _I think closest 10 is good. If anything I'd error on the side of closer. If you open up Google Maps on your phone (or even your computer) it isn't going to show you the whole city._
- **Zip/muni search:** Can we adjust for zip/muni searches to include the center point of the search? I believe in testing these searches were interpreted as a way for users to center themselves on the map, and some of these are giving less than desirable results: - _Do you mean just to include the center point in the fitbounds or do you mean add an icon showing the center point location?_

**Comment by versatilehuman** [comment]
Looks good. 

For zip/muni search I just mean to include the center point in the fitbounds to make sure the zip/muni is included within the resulting area.

**Comment by shua123** [comment]
Okay. Added search location to bounds group https://github.com/smartchicago/trailsy/commit/dab42b0e0c2b4814aa078beb98efe6426f1e569d

**Comment by versatilehuman** [comment]
So this is working for some, but not others.

Works: https://fpcc-staging.smartchicagoapps.org/#/?search=60602
![image](https://cloud.githubusercontent.com/assets/7032169/23364179/8dbc59cc-fcc3-11e6-9b05-5178b436f639.png)

Doesn't: https://fpcc-staging.smartchicagoapps.org/#/?search=60640
![image](https://cloud.githubusercontent.com/assets/7032169/23364218/c453fc4c-fcc3-11e6-9b2e-007e782b5ea4.png)

**Comment by versatilehuman** [comment]
Looks like this is working.
