### ISSUE TITLE
Panel height 

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#150]
Panel is cutting off the social at all sizes I've looked at... maybe related to the closing div/styling issue from when v2 went live?

![image](https://cloud.githubusercontent.com/assets/7032169/23265619/c7329372-f9aa-11e6-965d-8db9b5c8daf8.png)

![image](https://cloud.githubusercontent.com/assets/7032169/23265636/d3e309b2-f9aa-11e6-914f-6cbf17a6df14.png)

![image](https://cloud.githubusercontent.com/assets/7032169/23265647/dea97318-f9aa-11e6-8697-d9da366915d1.png)

**Comment by shua123** [comment]
This should be fixed https://github.com/smartchicago/trailsy/commit/1dc25c5c19ebcef2ed9e591ffd334bea73831ce7
