### ISSUE TITLE
Muni/zip matches reloading page if user declines to share location

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#157]
I've replicated this in multiple browsers on dev & gh-pages:

If you don’t share location and execute a search that matches muni/zip lists:

Muni/zip search leads to page reload (or activates the loader?) then never loads:

![image](https://cloud.githubusercontent.com/assets/7032169/23381810/862fce68-fd05-11e6-820f-8074c928709f.png)

If you manually reload it gives you this (trails have been removed) and fitbounds not adjusted:
 
![image](https://cloud.githubusercontent.com/assets/7032169/23381830/97ddb102-fd05-11e6-88d6-b1dc7f88c140.png)

**Comment by shua123** [comment]
This is fixed with https://github.com/smartchicago/trailsy/commit/eaf73b1d60394334048d6a456dc4f7bee3666e91
