### ISSUE TITLE
Fitbounds hiding sign & activity icons behind panel

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#158]
Not sure if there was an adjustment made, but it seems the fitbounds are not accounting for the panel, so the sign is often fully hidden behind the panel. Activities are often hidden too.

Example:
![image](https://cloud.githubusercontent.com/assets/7032169/23381918/e9f13752-fd05-11e6-950b-eba65a36fb6b.png)

**Comment by versatilehuman** [comment]
Here's a search example:
![screen shot 2017-02-27 at 8 12 35 pm](https://cloud.githubusercontent.com/assets/7032169/23388667/2e1b125e-fd29-11e6-9f2e-95b858bbf445.png)

**Comment by shua123** [comment]
Updated padding in place: https://github.com/smartchicago/trailsy/commit/da5abd3a8a3b0426af5d25cc7274d438903734f8

**Comment by versatilehuman** [comment]
Looks good on selected POIs/zoomed in. 

Initial load looks like a little too much padding (pretty zoomed out), especially the slimmer panel (width: 900px - 1150px).

I can't upload screenshots right now... GitHub is having issues too https://status.github.com/

**Comment by shua123** [comment]
I re-did this to calculate based on width of the panel https://github.com/smartchicago/trailsy/commit/b97d6abe7dfa936de8359858b4ce32223d47c119
