### ISSUE TITLE
Miller meadow weird codes

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#162]
I don't see anything in the trails table that would be causing this... thoughts @shua123?

![image](https://cloud.githubusercontent.com/assets/7032169/24979908/a0ff6c86-1f9b-11e7-93a3-fe0001872624.png)

![image](https://cloud.githubusercontent.com/assets/7032169/24979946/c49914c6-1f9b-11e7-8e83-45288146539e.png)

**Comment by shua123** [comment]
It looks like these (and a bunch of other stuff) were in the Direction column in the last trails data update I received from Garret. The github repo version of the data looks okay though. I'll update with that data.

**Comment by shua123** [comment]
This is fixed.
