### ISSUE TITLE
Add PDF fishmap to POI panel

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#164]
IF has link in fish_map column in poi_desc table, display in the "More Information" section of POI panel just after map_link, map_link_spanish and picnic_link. 

`<a class="fpccMore" href="[fish_map]" target="_blank">Fishing Lake Map (PDF)</a>`

![image](https://user-images.githubusercontent.com/7032169/27967396-80bd813c-6308-11e7-80df-c15641160e09.png)

**Comment by shua123** [comment]
Available on staging for review.

https://github.com/smartchicago/trailsy/commit/7b785dbd2f71cc920cfd80b71a87a54169ae628d

**Comment by versatilehuman** [comment]
Good to go.

**Comment by shua123** [comment]
In production https://github.com/smartchicago/trailsy/commit/d92a30fdd57eb6d2e507f6b05593d196eb20fcb0
