### ISSUE TITLE
Add picnic grove capacities to picnic grove popups on map

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#165]
If something in **capacity** column in **picnicgroves** table, add capacity value into picnic groves popup on map as follows:
 
```<div class="leaflet-popup-content" style="width: 145px;">```
 ```<div class="picnicgrove-popup">Deer Grove Grove #5</div>```

 
**Add:** ```<div class="picnicgrove-capacity">Capacity: [from capacity column in picnicgroves table]</div>```

 ```</div>```

+++

Then to style, add `.picnicgrove-capacity` class to lines 333 & 334 in newguts.css

`.trail-popup .trail-popup-line-named,.picnicgrove-capacity {
    border-top: none;
    padding: .5em .75em;
    width: 80%;
}`

`.trail-popup .trail-popup-line-named.trail-segment,.picnicgrove-capacity {
    border-top: 1px solid #e3e3e1;
    width: 100%;
}`

Visual: 
![image](https://user-images.githubusercontent.com/7032169/27967970-b20a93e0-630a-11e7-88e6-5acec092c70a.png)

**Comment by shua123** [comment]
This is now available on staging. 

https://github.com/smartchicago/trailsy/commit/d4eb5216434ac975482e3770e20d6e94e29c9d0b

**Comment by versatilehuman** [comment]
This is good to take live.

**Comment by shua123** [comment]
In production https://github.com/smartchicago/trailsy/commit/d92a30fdd57eb6d2e507f6b05593d196eb20fcb0
