### ISSUE TITLE
Add disc golf page link to POI panel

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#166]
If 1 in **disc_golf** column in **points_of_interest** table, display link to Disc Golf web page in "More Information" list. Put in alpha order among other activity links.

`<a class="fpccMore" href="http://fpdcc.com/disc-golf/" target="_blank">Disc Golf</a>`

![image](https://user-images.githubusercontent.com/7032169/27968396-76ff5c66-630c-11e7-9ee0-f7e4f3972bd2.png)

**Comment by shua123** [comment]
Available on staging for review.

https://github.com/smartchicago/trailsy/commit/4e9fb0ca8644d92b48b008e5a23c5ec496b90605

**Comment by versatilehuman** [comment]
Good to go.

**Comment by shua123** [comment]
In production https://github.com/smartchicago/trailsy/commit/d92a30fdd57eb6d2e507f6b05593d196eb20fcb0
