### ISSUE TITLE
Add ability to post an alert to all POIs & Trails

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#168]
Admin level only.

**Comment by versatilehuman** [comment]
Examples we've done in the past would be dangerously cold weather or major flooding like we experienced in the past few weeks. Where it's either a:

- General PSA -- hey it's really cold, we aren't closed but please don't visit
- General conditions -- we can't provide detailed flooding information for every trail, but just know that with recent rains you are likely to run into some.

++++

Maybe we can treat this as a separate kind of alert based on info below?

**adminserver alert poi/trail lists:** No, would want this listed separately. New nav tab/page?

**map search of places with active alerts:** No

**Wordpress list of all alerts:** Yes, but only once. Could display like:

LIST OF ALL ALERTS & CLOSURES
- [DISPLAY GLOBAL alerts]
- [DISPLAY ALL poi/trail alerts]

**Wordpress "Display POI/Trail specific alerts"**: Could display like:

SINGLE POI/TRAIL ALERTS
- [DISPLAY SINGLE poi/trail alerts]
- [DISPLAY GLOBAL alerts]

Also, would want these listed as single instances in the "All Alerts" section and the backups we're doing:

![image](https://user-images.githubusercontent.com/7032169/28787088-da958f70-75e0-11e7-84a7-c894064d5ce4.png)

**Comment by shua123** [comment]
What does the form/options look like for this? Is it always an alert (never a closure)? Any pre-created Issues for a drop down?

Fields?: Issue, Description, Link, Start Date, End Date

**Comment by versatilehuman** [comment]
- Description
- Link
- Start Date
- End Date

**Comment by shua123** [comment]
Added a Global Alerts page for admin to create and display global alerts. On staging. They will also show up on staging map.

https://github.com/smartchicago/trailsyserver/commit/ba41ffafa72be9f56e465ca5be3fd763d14289b2

**Comment by versatilehuman** [comment]
Looks good.
