### ISSUE TITLE
Add map search view displaying only locations/trails with active alerts

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#169]

**Comment by shua123** [comment]
Filters pois and trails based on alerts https://github.com/smartchicago/trailsy/commit/3a93ab7cdc623bf70cb45efe137103a9e70ded4c

It will filter for alerts if there is "hasalerts" or "hasAlerts" as a search term. In other words, https://fpcc-staging.smartchicagoapps.org/#/?search=hasAlerts . It generally should work in coordination with other filters.
