### ISSUE TITLE
Create embed for list of all alerts

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#173]

**Comment by shua123** [comment]
Added separate json output structured for the list: https://github.com/smartchicago/trailsyserver/commit/a1bbbd0414c806fddb1b5dd2fc642dc3e09cea3f

Developing basic html page/list that can be embedded https://github.com/smartchicago/trailsy-vis

**Comment by versatilehuman** [comment]
@shua123 This looks good. Do we need to style it on the embed side or will we be able to do it on fpdcc.com?

**Comment by shua123** [comment]
Easiest would be to just do it on the embed at least to start.

To get css from the parent to the iframe the iframe has to pull the parent's css through javascript. I haven't tried that yet though.

**Comment by versatilehuman** [comment]
I need to provide styling.

**Comment by versatilehuman** [comment]
This looks good. Can we wrap the POI/Trail names in <h4> and update to this:

` a{color: #424d1d; text-decoration: underline}
a:hover,a:focus{color: #23527c;text-decoration:none}
.h4, .h5, .h6, h4, h5, h6 {margin-top: 20px;margin-bottom: 10px}
`

**Comment by versatilehuman** [comment]
Can we also change "Global Alerts" to "General Alerts"

**Comment by shua123** [comment]
Updates made.

**Comment by versatilehuman** [comment]
Can you wrap General Alerts in `<h4>` too. You can also eliminate the `<strong></strong>` on all the POI-Trail names.

**Comment by shua123** [comment]
Styling updated: https://github.com/smartchicago/trailsy-vis/commit/38b3f056e7f87ccab096c8f75aaf8b2cab1ea43b

**Comment by versatilehuman** [comment]
How are these ordered? Can we get them in alpha order?

**Comment by shua123** [comment]
I've updated the list json to order all POIs by name, then all trail systems by name.
https://github.com/smartchicago/trailsyserver/commit/710814d1db8ff200884b783ae13781f3f81669bd

**Comment by versatilehuman** [comment]
That works. I tested on the site and we are good. Is this going to live on GitHub or be moved to the production server?
