### ISSUE TITLE
Add issue dropdown option for parking lot repair

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#175]
Should be available for all levels of users.

**Display in dropdown:**
CLOSED: Parking lot repair/repaving

**Populate description with:** 
Parking area closed for repair/repaving.

**Comment by shua123** [comment]
On staging https://github.com/smartchicago/trailsyserver/commit/2acd156d0fc5939b78487c2f5cd8f9649c9ac255

**Comment by versatilehuman** [comment]
Looks good
