### ISSUE TITLE
Trail alerts need period at end

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#176]
Trail:
![image](https://user-images.githubusercontent.com/7032169/29079084-d19f0058-7c21-11e7-8043-08f062815730.png)

POI: 
![image](https://user-images.githubusercontent.com/7032169/29079110-e377bf72-7c21-11e7-846f-c245861d4e7c.png)

**Comment by shua123** [comment]
This should be okay on staging now.
https://github.com/smartchicago/trailsyserver/commit/23f9fa3a3da28131dd18b10be8e52929e1ff7baa
