### ISSUE TITLE
Link POI names in Trail alert text

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#177]
We had discussed this but think it got lost. This would link any POI names in Trail Alerts only. To help people zoom to the area that is impacted vs. needing to search manually for the trail segment impacted. 

![image](https://user-images.githubusercontent.com/7032169/29078524-44b1ba42-7c20-11e7-9ee7-5127b9780bcc.png)

Another idea would be to be to have another form field that we could enter the lat/long of the specific location impacted. This would be more precise, but not sure how much work would be involved to make that functional:

![image](https://user-images.githubusercontent.com/7032169/29078869-2dffb758-7c21-11e7-8f55-fd25a2a3ae6c.png)

![image](https://user-images.githubusercontent.com/7032169/29079190-1ac7d142-7c22-11e7-929c-963c8af154a4.png)

![image](https://user-images.githubusercontent.com/7032169/29079288-5f2d8b06-7c22-11e7-8fa9-c7f07e53e9b3.png)

**Comment by shua123** [comment]
Added links to pois in alert description on staging.

https://github.com/smartchicago/trailsyserver/commit/23f9fa3a3da28131dd18b10be8e52929e1ff7baa

**Comment by versatilehuman** [comment]
Looks good, but can't use browser back button when starting at a trail and clicking through to a POI:
https://fpcc-staging.smartchicagoapps.org/#/?trail=Des+Plaines+Trail+System

Works when starting at a POI and clicking through to another POI:
https://fpcc-staging.smartchicagoapps.org/#/?poi=364-Big+Bend+Lake

Similar to: https://github.com/smartchicago/trailsy/issues/66#issuecomment-259543702

**Comment by shua123** [comment]
Browser back button should be working now. This was an unrelated bug with the external change script.
https://github.com/smartchicago/trailsy/commit/e174463b2faf13a853d1d85f6bb44a14351a3d97

**Comment by versatilehuman** [comment]
Looks good.
