### ISSUE TITLE
Update alert error messages

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#179]

**Comment by versatilehuman** [comment]
@shua123 Do you have a full list of the current language you can pull easily?

**Comment by shua123** [comment]
@versatilehuman Not really, but there is kind of a default pattern for form validation based on the validation type. Generally it is "FIELD_NAME MESSAGE." For validations that require the field to not be blank the message defaults to "can't be blank." Using your screenshot (below), because the field we are actually checking is "Alert type" that is what is showing for field name with the can't be blank. You can see the alert validations at https://github.com/smartchicago/trailsyserver/blob/alerts20/app/models/alert.rb#L19. Note the custom message for the website url field (https://github.com/smartchicago/trailsyserver/blob/alerts20/app/models/alert.rb#L26)

For the second example in the screenshot, the validation is on the Alertings model. Alertings is the table that stores the connections between an alert and an poi/trailsystem. In this case its checking if the alerting can be saved but it can't because its associated alert can't be saved. Its essentially double notifying about the same alert issue. I'll see what to do about that.

![image](https://user-images.githubusercontent.com/1593537/30555928-be524330-9c6e-11e7-9092-686de25a57f8.png)

**Comment by shua123** [comment]
Updated messages.
https://github.com/smartchicago/trailsyserver/commit/c7c3c8038ccd2f926026bbb320a553089afb977e
