### ISSUE TITLE
Link directing to malware site?

### ISSUE THREAD

**Issue by OpenGlobe** [smartchicago/trailsy#18]
"Tothetrails.com" appears to be redirecting to a Malware site off the readme.md  -

<img width="915" alt="screen shot 2016-01-26 at 5 23 31 pm" src="https://cloud.githubusercontent.com/assets/5495118/12597294/66a5aa82-c452-11e5-8ecb-08c2341c0476.png">

**Comment by shua123** [comment]
Thanks. I removed the link from the readme.
