### ISSUE TITLE
Minor map alert issues

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#182]
- [x] Trail alert box (on POI panel) shaking
- [x] Update "no end date set" language

## Trail alert box (on POI panel) shaking
On POI panels with Trails on them, when you expand the POI alert box, the Trail alert box also expands (reverse is also true). Wouldn't be a big deal, but it seems it is making the panel shake when you expand the Trail alert box (tested in Chrome). Example POI:

https://fpcc-staging.smartchicagoapps.org/#/?poi=337-Allison+Woods

![image](https://user-images.githubusercontent.com/7032169/31519817-3b38dbe0-af69-11e7-9ab9-c505a38a4652.png)

## Update "no end date set" language
Can we update "no end date set" to "???"

from:
![image](https://user-images.githubusercontent.com/7032169/31519861-70927fbc-af69-11e7-9cf1-42787f0463df.png)

to:
![image](https://user-images.githubusercontent.com/7032169/31519949-c4585040-af69-11e7-92ff-a4f828477613.png)

**Comment by shua123** [comment]
Both done.
https://github.com/smartchicago/trailsy/commit/0f10c588acb8e9696b4ae3e13828a994e17b8711
https://github.com/smartchicago/trailsy/commit/513e0c5358b4bf5895762200b6d53e22e0f407d8
