### ISSUE TITLE
Remove X from popups

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#183]
After alert system went live these appeared in all popups (activities, pois, trails):

![image](https://user-images.githubusercontent.com/7032169/32227971-d1947044-be1a-11e7-93b0-a64acee9528f.png)

Before
![image](https://user-images.githubusercontent.com/7032169/32227640-f450cf0c-be19-11e7-8a45-6399a94bbc97.png)

Not sure how we were hiding this before. Class is `leaflet-popup-close-button`

**Comment by shua123** [comment]
Done on staging: https://github.com/smartchicago/trailsy/commit/9498ccba206df0c4184ed744d5caa31b46f0e6a5

**Comment by versatilehuman** [comment]
Looks good.

**Comment by shua123** [comment]
Deployed
