### ISSUE TITLE
Update alert end date

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#184]
Based on feedback from staff, can we reduce to a single question mark (vs. current ???)

![image](https://user-images.githubusercontent.com/7032169/32450669-673765c0-c2da-11e7-83f7-cb73df005c96.png)

**Comment by shua123** [comment]
Map updated on staging https://github.com/smartchicago/trailsy/commit/2aa7a82f46ff97e78641bcc0bacccdd7d27dd538

**Comment by versatilehuman** [comment]
Good to go.

**Comment by shua123** [comment]
Deployed
