### ISSUE TITLE
Alert admin on mobile

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#187]
To fix a layout issue, add clear property in these two places:

```
.navbar-nav {margin:7.5px -15px;clear:both}

@media (min-width: 768px) {
.navbar-nav{float:left;margin:0;clear:none}
}
```

**Comment by shua123** [comment]
on staging for review https://github.com/smartchicago/trailsyserver/commit/6cad3cc2e1bb0811e981368415dd3c8fe0f59f91

**Comment by versatilehuman** [comment]
Good to go.
