### ISSUE TITLE
Change equestrian wording in panel

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#188]
Update to **Equestrian Parking** in panel:

![image](https://user-images.githubusercontent.com/7032169/32630417-24155ede-c562-11e7-923a-106d332a0a63.png)

**Comment by shua123** [comment]
On staging 
https://github.com/smartchicago/trailsy/commit/868c8b8801ad4f62484937671ab93648bff17b62

**Comment by versatilehuman** [comment]
Good to go

**Comment by shua123** [comment]
Deployed
