### ISSUE TITLE
Trail alert phrasing

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#189]
After using this for a little while, many of the construction closures can have awkward explanations that don't fit the default phrasing we set up. Can we eliminate "on" when we append the trail and POI names to the end? This gives some needed flexibility when phrasing these.

So instead of:

> on Des Plaines Trail System - Olive Unpaved Spur (North) and Orange Unpaved (North) near Dam No. 1 Woods-East.

We use:

> Des Plaines Trail System - Olive Unpaved Spur (North) and Orange Unpaved (North) near Dam No. 1 Woods-East.

**Comment by shua123** [comment]
on staging

**Comment by versatilehuman** [comment]
Sorry, missed this. Good to go.
