### ISSUE TITLE
No search dropdown on mobile

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#191]
This is occurring on staging & production consistent on my Android with Chrome, Windows Desktop Chrome, iPhone SE Safari.

![image](https://user-images.githubusercontent.com/7032169/32807913-1944104c-c957-11e7-8962-6f56f95e2cbf.png)

**Comment by shua123** [comment]
Got a fix on staging for testing. https://github.com/smartchicago/trailsy/commit/3179932d4fa7fe2fdfcdf64d97f90e28db264f58

**Comment by versatilehuman** [comment]
This looks good, thanks for the quick work.

**Comment by shua123** [comment]
Deployed
