### ISSUE TITLE
Add data link to about section

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#192]
Let's edit this section to add a link to the data:

```
<p>Smart Chicago consultant <a href="http://www.smartchicagocollaborative.org/people/consultants/current-consultants/josh-kalov/">Josh  Kalov</a> is the main developer on this project.</p> 
<p><a href="https://github.com/smartchicago/trailsy/">View the project’s GitHub page</a> or <a href="https://github.com/fpdcc/webmap_data_updates">download Forest Preserves web map data</a>.</p>
```

**Comment by shua123** [comment]
On staging https://github.com/smartchicago/trailsy/commit/1d07906fe8190baef30d027b573d29c4af16e929

**Comment by versatilehuman** [comment]
Need to remove the first instance of "View the project's..." then good to go:

![image](https://user-images.githubusercontent.com/7032169/32899707-4c7d2d9e-cab1-11e7-8574-0fae863ffa60.png)

**Comment by shua123** [comment]
Fixed https://github.com/smartchicago/trailsy/commit/0ceeefb16ca520dd3e0fa771eaee2f6c493e9103 and deployed
