### ISSUE TITLE
Search box dropdown misaligned on desktop

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#193]
Maybe result of #191 fix. The dropdown creeps up about 10px:

![image](https://user-images.githubusercontent.com/7032169/33443730-e95fb1c4-d5bd-11e7-89e6-7cc54e46882d.png)

![image](https://user-images.githubusercontent.com/7032169/33443736-ecb572aa-d5bd-11e7-9d74-e3e2e7e8bba9.png)

If we bump up to top:38px here, it works on desktop (not sure how that will impact mobile):

![image](https://user-images.githubusercontent.com/7032169/33444053-c9a5cf02-d5be-11e7-95e3-27fc83d67f32.png)

There is already a bit of a gap (4px) between the dropdown and input on mobile:

![image](https://user-images.githubusercontent.com/7032169/33444298-7f5d479e-d5bf-11e7-94bb-30f16ed93a22.png)

**Comment by versatilehuman** [comment]
@shua123 Can you take a look when you have a chance?

**Comment by shua123** [comment]
@versatilehuman  I tweaked this some. Check out staging.

**Comment by versatilehuman** [comment]
Looks good as far as positioning, still need padding restored here to match the other dropdown items. Looks like it has a `create` class on it and should be `padding:5px 8px`:

![image](https://user-images.githubusercontent.com/7032169/35229469-20ea5300-ff59-11e7-913a-ae7bec2ba93f.png)

![image](https://user-images.githubusercontent.com/7032169/35229492-2c117ede-ff59-11e7-8fa5-e79b78bac1d4.png)

**Comment by versatilehuman** [comment]
Also minor, I'm getting the text cursor when hovering on selectable dropdown options, should add `cursor: pointer` on the `.option:hover` state.

**Comment by versatilehuman** [comment]
This all looks great.
