### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#196]
I get this in Chrome any time I click the "Back to List >" link:

![image](https://user-images.githubusercontent.com/7032169/37168095-673e7f32-22c9-11e8-80a9-607008e129de.png)

It is not impacting any functionality as far as I can tell.

**Comment by shua123** [comment]
I see this on production but not on staging or my local dev version. Are you seeing this on the latest staging? If not I'll hold off doing anything here till we push the latest staging to production.

**Comment by versatilehuman** [comment]
Don't see it on staging, getting this instead:

![image](https://user-images.githubusercontent.com/7032169/37299072-3eba8860-25f0-11e8-8487-2148ad16807d.png)
