### ISSUE TITLE
Evaluate using Cook GIS Aerial imagery

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#198]
Currently we have MapBox satellite imagery as an option users can turn on. One alternative to MapBox satellite is to use aerial imagery from Cook County GIS that is published on Cook Central at https://hub-cookcountyil.opendata.arcgis.com/datasets/d24c45548fdc42e8a24a5ed2c7e7738f. 

At https://fpcc-staging.smartchicagoapps.org/ccimagery/index.html I have added an "Imagery" option to the layers options in the bottom right corner. Clicking on this will show imagery from the Cook GIS service. There are several options available like changing the [jpg compression quality](https://github.com/smartchicago/trailsy/blob/cc-imagery/js/map.js#L139) so we can tweak it a bit. 

Let me know what you think @versatilehuman @glw

**Comment by versatilehuman** [comment]
Love it. It's a little slow, but I'd image we can speed it up with the tweaks to compression quality.

@shua123 Did you ever pull #s on how many users were toggling to satellite?

**Comment by shua123** [comment]
Unfortunately we weren't capturing base layer changes in analytics. I've added that (https://github.com/smartchicago/trailsy/commit/b5ad0a908590a6bdc687fb828323be8c67841bb7) in development so it will start tracking when we move the current development changes to production.

**Comment by versatilehuman** [comment]
Sounds good.

**Comment by shua123** [comment]
We switched to using Cook County's [2017 Aerial Imagery](https://hub-cookcountyil.opendata.arcgis.com/datasets/ee51815fb509461cb5f20714c7f0da98) in production. Server response is a little slow.
