### ISSUE TITLE
handle unpaved and primitive trails differently

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#21]
From Ryan: "Unpaved and primitive trails will be rendered as dotted (is this possible on the map itself?)
Dotted style for unpaved and primitive trails in panel (in the new CSS I’m sending): .fpccUNPAVED,.fpccUnpaved,.fpccPrimitive,.fpccPRIMITIVE{border-bottom-style:dotted}"

**Comment by shua123** [comment]
This is active as of https://github.com/smartchicago/trailsy/commit/4d2666f8af6e729ea1ba8fc68da1aece9c91dfe2 . There are still several other trail_types beyond paved, unpaved, and primitive

**Comment by versatilehuman** [comment]
Covered in #97
