### ISSUE TITLE
Clicking on trail shows entire trail length vs features of that trail

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#27]
This relates to work done in issue #5. When clicking on the trail, my expectation was to get information about that trail (such as paved/unpaved, activities, etc). I was not expecting it to zoom to the full trail and it was difficult then to go back to where I was before. 

A couple of initial questions to consider when designing the navigation:
- What value does a user get when seeing the entire trail?
- Is there an easy way to get the user to go back to their last view?
- Would it make sense to show smaller sections of the trail?

I think highlighting this information would be important:
<img width="375" alt="screen shot 2016-02-15 at 12 30 35 pm" src="https://cloud.githubusercontent.com/assets/5550969/13057180/119c8072-d3e0-11e5-88f9-9876472c8b3b.png">

**Comment by shua123** [comment]
@smarziano when you click on a trail on the map?

**Comment by smarziano** [comment]
Correct, @shua123. I clicked on "LaBagh Woods" which took me to the entrance marker, and then I clicked on the red trail expecting more information but was led to a view of the entire trail.

**Comment by shua123** [comment]
I am going to change zoom to not zoom out on click.

The 2nd question is what do about a popup for trail click. It may make sense to duplicate some of the details from the detail panel into a popup. Or maybe have the popup be more segment focused?

**Comment by versatilehuman** [comment]
I think both. Reiterate the important panel info and then provide more
segment information in the popup (trail difficulty comes to mind).

**Comment by shua123** [comment]
Okay. I have dropped the zoom out. I have also added a popup to the trails. Right now it just shows the trail system name.

https://github.com/smartchicago/trailsy/commit/e5168e3de3e0b4620ca9cb411a5aa4003ae2f377

**Comment by versatilehuman** [comment]
Zoom issues covered in #56. Closing and creating new (long term) enhancement for trail difficulty/segment info. #107.
