### ISSUE TITLE
Google Analytics 4 (GA4) & Tag Manager Implementation

### ISSUE THREAD

**Issue by alxstockdale** [smartchicago/trailsy#279]
- Need to install Google Analytics 4 (GA4) code snippet and ensure it is loaded on every page to enable sitewide tracking for the web map.
- Original Google Analytics Univeral Analytics (UA) can be left as-is in its JavaScript file until the sunset by Google. No harm in leaving that to/post expiration, with Google Analytics 4 (GA4) running in parallel.

**Comment by gisdevcc** [comment]
@alxstockdale We finished this correct? Can we close it?

**Comment by alxstockdale** [comment]
Yes, we can close this. Data has been flowing successfully.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
