### ISSUE TITLE
Zooming in and out is limited when using mouse scroll wheel or trackpad

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#28]
Using a mac trackpad or a mouse with a scroll wheel on my pc, I am limited to a certain zoom level and cannot zoom in or out. I am forced to use the zoom out button on the map.

**Comment by shua123** [comment]
Scrollwheel zoom was turned off in the original Code For America version do to offset zooming. Need to investigate this more. Related: https://github.com/codeforamerica/trailsy/pull/121

**Comment by shua123** [comment]
Okay. I've turned it back on. Lets see how it goes..

**Comment by shua123** [comment]
Scroll zoom does in fact act weird due to offset zooming. Leaving it on for now but need to investigate custom scroll zoom or alternative.
