### ISSUE TITLE
Idea: Clicking on activity icon in detail panel pans to activity point

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#29]

**Comment by shua123** [comment]
This will be discussed in #56

**Comment by versatilehuman** [comment]
This is only relevant for certain activities in a fraction of locations. 

Desktop: with zoom/pan guidelines in place, activity locations should be apparent and further zooming/panning may not be desirable or meet user expectations.

Mobile: implementation could be difficult zoom/pan + hide panel. May not meet user expectations.
