### ISSUE TITLE
Clicking on activity icons does not provide additional information

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#30]
When navigating the map, I am unable to click on the activity icons to get more information.

**Comment by versatilehuman** [comment]
Initially we discussed a click on the activity icons pulling up the panel
info for that location (if it wasn't already there). But there should be a
consistent function every time someone clicks. Even just a pop-up with the
name of the activity to start. We can see what other useful information we
can add to that. I'm thinking capacities for picnic groves, hours for
buildings, rates for boat rental. Things that are specific to the activity,
but not necessarily the whole location.

**Comment by shua123** [comment]
Added a popup to activities that shows the activity name. https://github.com/smartchicago/trailsy/commit/71c8b369c32f88a2e9f712d2415871bbfb10d10a

**Comment by smarziano** [comment]
@shua123 Activity names are also now listed under the icon. Not sure if that is intentional.

**Comment by shua123** [comment]
It was for testing. A couple activity types will have names with the icons
