### ISSUE TITLE
Clicking on logo should lead to homepage

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#31]
While navigating the site, I tended to navigate too far away from where I started and wanted to go back to the start. A couple of times I caught myself clicking on the Forest Preserves logo to go back to the homepage view, but nothing happens. My expectation is that clicking the logo will lead to the homepage view, but this is more of a question for now and something I want to keep an eye on with CUTGroup testers to see if this is something that they also try to do.

**Comment by shua123** [comment]
This makes sense and is easy to do. Thoughts @versatilehuman?

**Comment by versatilehuman** [comment]
Sounds good. May need to rethink once connected to non-map part of the
website.

**Comment by shua123** [comment]
Okay, I've added in a refresh link on the logo. https://github.com/smartchicago/trailsy/commit/28b95f0d9758013dbda0a00d1ad65a0410b3e39d

**Comment by versatilehuman** [comment]
@shua123 This got removed on the major html/css update.

**Comment by versatilehuman** [comment]
@shua123 Want to make sure this is re-implemented.

**Comment by shua123** [comment]
Added this back in with https://github.com/smartchicago/trailsy/commit/7e67c1fb5d10550a230baf477109e685c0f56402
