### ISSUE TITLE
Missing "Current Location" button

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#32]
Find current location button is missing.
<img width="72" alt="screen shot 2016-02-15 at 5 17 00 pm" src="https://cloud.githubusercontent.com/assets/5550969/13062889/fafa0cb8-d407-11e5-849c-31da352012d3.png">

**Comment by versatilehuman** [comment]
@shua123 This disappeared again and I haven't been prompted for location in a while... can't remember if this was shut off for a reason.
