### ISSUE TITLE
Distance away is always from "Current Location"  

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#33]
Once you click on a result, you are moved away from your "Current Location," but the miles away on the results page are always from your "Current Location."

Here is an example of results list after clicking on LaBagh Forest:
<img width="1218" alt="screen shot 2016-02-15 at 5 37 34 pm" src="https://cloud.githubusercontent.com/assets/5550969/13063181/f88be714-d40a-11e5-848f-db5608fbc66f.png">

This is something that we can ask about in testing, too. Also, would be good to investigate what makes sense when people do not allow the site to use their current location.

**Comment by versatilehuman** [comment]
If you search for a municipality or zip code, it moves you to that area and recalculates miles away from there. Based on behavior during testing. Should revisit at some point.
