### ISSUE TITLE
Links/images on pop-ups/tool-tips

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#35]
![image](https://cloud.githubusercontent.com/assets/7032169/13118464/dfeb064e-d569-11e5-8d5c-1eb66c9a7fba.png)

Remove "To the Trails" icon:
`<img class="calloutTrailheadIcon" src="img/icon_trailhead_active.png">`

Update fonts, add trail access icon, other style changes:
I'll provide CSS/HTML

**Comment by shua123** [comment]
Fix link to trail
