### ISSUE TITLE
Consistently show search/filter functions on result page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#36]
When a user reaches a result item (ex: Irene C. Hernandez Family Picnic area), an ability to quickly search should always be shown at the top. It might not be intuitive to users that they have to "X" out of that result page to get back to their search and results pages. This will be a good thing to look out for during testing.

Here is the result item:
<img width="1198" alt="screen shot 2016-02-17 at 1 30 47 pm" src="https://cloud.githubusercontent.com/assets/5550969/13122050/b2c3f160-d57a-11e5-99df-d783a648989f.png">

Right above the name of the location I would add:
Filter: Activity/Amenity
Search box
"279 results found" _(With an ability to click and see all results again)_

**Comment by shua123** [comment]
@versatilehuman is working on a mock up that would keep search box on screen.
