### ISSUE TITLE
customize basemap to remove chicago park district & cook county names

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#40]

**Comment by smarziano** [comment]
During the CUTGroup test, I had one tester who chose "Columbus Park" (which is a Chicago Park District) as the closest Forest Preserve near her. We talked about removing the names, but she suggested either greying that part of the map out and making the Forest Preserves green a higher contrast. I think both options would work.

**Comment by smarziano** [comment]
This might be related to this issue: we also saw testers click on the map's city names to try to see results near that location or have the map zoom and center on that location,

**Comment by versatilehuman** [comment]
I also saw this contribute to issue #43 with a few testers, where they assumed activities where available at a location because of proximity to the label on the map.

**Comment by versatilehuman** [comment]
See #60
