### ISSUE TITLE
What should be on the map after filtering/search?

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#41]
Right now all the activities stay on the map during filtering/search.

For example, after filtering for hiking, you can still see activities at locations that don't have hiking trails:

![image](https://cloud.githubusercontent.com/assets/7032169/13226097/68f4df02-d955-11e5-9080-4af8b186c99b.png)

Can we de-clutter the map based on filter/search? This would need to be paired with better access to search/reset (as discussed).

**Comment by shua123** [comment]
As of https://github.com/smartchicago/trailsy/commit/c6257ccb7259d805ada1b1a25541caf90e01507e I am only showing activties for entrances that show up in search results.
