### ISSUE TITLE
Search/Fliter/Reset presence in panel

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#42]
Need to figure out a way for the search/filter to have a constant presence in the panel to allow people to jump back to search when needed. I'll provide mock-ups for potential solutions.

**Comment by shua123** [comment]
Is this a dup of #36 ?

**Comment by versatilehuman** [comment]
Yes, sorry. Deleting.

**Comment by versatilehuman** [comment]
dup of #36 , closing
