### ISSUE TITLE
Which activities belong with which entrance?

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#43]
I'm having trouble quickly evaluating which activities are actually available at each entrance, especially in areas with multiple preserves close together.

**Potential solution:** Perhaps the activity icons are greyed out until an entrance is selected, then those activities are changed to full color? This could also be helpful for trails (starting out grey/green, then changed to color when selected).

**Comment by versatilehuman** [comment]
This would be good to implement for search/filter too. Right now at certain zoom levels, activities outside of the search/filter parameters are still present. Could grey out all non-relevant results.

**Comment by shua123** [comment]
I will be investigating greying out activities.

**Comment by versatilehuman** [comment]
@shua123 Thoughts:

- Entrance signs always stay in color
- On map load, all activity icons start out grey
- If an entrance icon or grey icon is clicked/touched, then all icons at that location ---> color

**Comment by versatilehuman** [comment]
In congested areas, this still may be confusing if entrance signs always stay in color. May need a highlighting scheme for them as well (circle around active entrance or something?)

**Comment by shua123** [comment]
Using opacity to "grey" out the activities. Up on staging.

**Comment by versatilehuman** [comment]
@shua123 Would like your thoughts. I still think we need something that highlights the entrance and activities that are currently displayed in the panel (the can a swim at Caldwell Woods problem).

Let me know if you think this is too much or too little or if you can think of another approach. 

When a user clicks/touches an entrance or activity icon, the whole set of icons related to that icon would highlight as shown below (proceeded by a slow animated blink):

![image](https://cloud.githubusercontent.com/assets/7032169/14900001/30d9b812-0d54-11e6-80af-14d54ec2a7a3.png)

Would need to change the on map icons with this:
```
.icon.icon-map{padding:.4em;width:3em;height:3em;}
.icon.icon-map.icon-sign{padding:.8em 0 0;}
```

Add the animation:
```
@keyframes animateEdge{0%{background:none;box-shadow:none;}33%{background:rgba(126,144,57,.45);box-shadow:0 0 7px 5px rgba(126,144,57,.45);overflow:visible;border-radius:3em}66%{background:none;box-shadow:none;}
100%{background:rgba(126,144,57,.45);box-shadow:0 0 7px 5px rgba(126,144,57,.45);overflow:visible;border-radius:3em}
@-webkit-keyframes animateEdge{0%{background:none;box-shadow:none;}33%{background:rgba(126,144,57,.45);box-shadow:0 0 7px 5px rgba(126,144,57,.45);overflow:visible;border-radius:3em}66%{background:none;box-shadow:none;}100%{background:rgba(126,144,57,.45);box-shadow:0 0 7px 5px rgba(126,144,57,.45);overflow:visible;border-radius:3em}
```

Then apply this to related icons when clicked/touched (add a class?)

```
.icon.icon-map.ADDEDCLASS{animation:animateEdge 2.5s forwards;}
.icon.icon-map.icon-sign.ADDEDCLASS{animation:animateEdge 2.5s forwards;}
```

**Comment by versatilehuman** [comment]
@shua123 Any thoughts on this?

**Comment by shua123** [comment]
@versatilehuman Sorry I thought I had responded to this. I like the highlighting. Not sure how I feel about the animated blink. I want to see how it looks.

**Comment by shua123** [comment]
I want to table out the scenarios like we did for the pan & zoom options

**Comment by shua123** [comment]
@versatilehuman thoughts? I might be missing some scenarios/options.

Scenario | Entrance Viewable | Entrance Opaque/Grey | Entrance Highlighted | Activities Viewable | Activities Opaque/Grey | Activities Highlighted
------------ | ------------- | ---------------- | ---------------- | ----------------------- | -------------- | ---------------
In Search Results | Yes | ?? | No | Yes | Yes? | No
Not in Search Results | No? | -- | -- | No? | -- | --
DetailPanel Open/Icon Click | Yes | No | Yes | Yes | No | Yes

**Comment by shua123** [comment]
As of commit https://github.com/smartchicago/trailsy/commit/c2663514c530a26796ad467375a7457eac8c8d7c the highlight/animation is implemented. 

This is on staging. Thoughts @versatilehuman ?

**Comment by versatilehuman** [comment]
I like it, but still would like feedback on animation. I think it's useful to draw attention to the highlighting. It's subtle, but may become annoying after a while (but our main use cases are probably quick visits to the map).

**Comment by versatilehuman** [comment]
I think this?

Scenario | Entrance Viewable | Entrance Opaque/Grey | Entrance Highlighted | Activities Viewable | Activities Opaque/Grey | Activities Highlighted
------------ | ------------- | ---------------- | ---------------- | ----------------------- | -------------- | ---------------
In Search Results | Yes | No | No | Yes | Yes | No
Not in Search Results | No | -- | -- | No | -- | --
DetailPanel Open/Icon Click | Yes | No | Yes | Yes | No | Yes

**Comment by shua123** [comment]
@versatilehuman Is the animation how you expected it? I don't think I changed anything from your code.

**Comment by versatilehuman** [comment]
@shua123 yes, I'm just always wary about including animations that will become repetitive. Maybe something to user test in the future?

**Comment by shua123** [comment]
Occasionally after un-selecting a POI/Entrance, a halo of the highlight/animation remains. 
![image](https://cloud.githubusercontent.com/assets/1593537/15460225/17d036b0-2074-11e6-957c-7640fa25ac4e.png)

**Comment by versatilehuman** [comment]
@shua123 I can't replicate this anymore. You?

**Comment by versatilehuman** [comment]
Closing--Still can't replicate this bug.
