### ISSUE TITLE
Search drop down persisting occasionally after selecting location from map (v3 search)

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#44]
Chrome 48.0.2564.109 m (64-bit), Windows 7 Enterprise

v3 of the search/filter

![image](https://cloud.githubusercontent.com/assets/7032169/13229676/b902dbcc-d967-11e5-83e4-abdb36ce23a0.png)

**Comment by shua123** [comment]
@versatilehuman  Have you encountered this at all recently? I think our panel changes and switch to selectize2 took care of this issue.

**Comment by versatilehuman** [comment]
@shua123 Missed this. Not seeing original issue. 

Playing around, I'm seeing this...

List disappears: 
- When selecting something from the list (or manually typing something that matches the list)
- When manually typing something in and hitting "Search" button

Least reappears:
- When manually typing something in and hitting "enter" on keyboard
- When manually typing something in and hitting "Add..." 

Seems like a convenience for users choosing multiple things and an annoyance for users choosing one. Maybe have it disappear for all scenarios after first search and only reappear if: (1) the user clicks elsewhere and then back to search box or (2) starts typing?

**Comment by shua123** [comment]
@versatilehuman I agree with your thoughts about having it always close. Unfortunately there does not seem to be a great way to do this. Trying with setTimeouts on staging right now...

(reference: https://github.com/selectize/selectize.js/issues/925)

**Comment by versatilehuman** [comment]
Looks better. Still getting it with zip searches. May be something we live with for now...

**Comment by versatilehuman** [comment]
Looks good. Closing.
