### ISSUE TITLE
Free search not fully filtering on map (v3 search)

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#45]
Free word search leaves non-results on the map (v3 of search/filter):

![image](https://cloud.githubusercontent.com/assets/7032169/13229850/65b9ff8a-d968-11e5-91ab-85aa0bb92a3e.png)

**Comment by shua123** [comment]
I am having trouble replicating this. @versatilehuman are you still experiencing this on the latest version on http://fpcc-staging.smartchicagoapps.org?

**Comment by shua123** [comment]
Yeah, I'm not seeing this anymore. Can I close this @versatilehuman ?

**Comment by versatilehuman** [comment]
@shua123 Yes
