### ISSUE TITLE
Allow users to search by city name or zip code

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#47]
From our CUTGroup test, multiple testers tried to use the search box to search by zip code, Chicago neighborhood name, or city name. Examples of when this happened include when testers were either looking for a nearby location (and typed "Cicero, IL") or wanted to find a Forest Preserve relevant to them and searched by zip code or neighborhood name.

Having more flexibility on the search to allow for zip or city name would be a helpful enhancement. Another option might be to more clearer about the search results in the panel being "Near you" or having some other "Near me" feature incorporated.

**Comment by shua123** [comment]
This came up a couple times in the tests I proctored. I want to read more about the expectation of this kind of search. If it is a question of "What are the things **in** Cicero" vs "what are the things **near** cicero"

What kind of neighborhood names were being searched? Chicago neighborhoods, suburban neighborhoods (I'm not sure if there really are any in the same way there are in Chicago)?

**Comment by smarziano** [comment]
My expectation of this kind of search is to find things **near** Cicero, IL. 

Once a tester tried to search by the name "Chicago," I know one tester tried to search for zip code, then started to search for "Rogers Park" but deleted the result since nothing was coming up as she typed.

I do not think searching by neighborhood name is important, but searching near a city or zip code is expected.

**Comment by versatilehuman** [comment]
Based on where preserves are located, there are a lot of cities and zip codes that would come up empty for the **in** search (including almost all Chicago zip codes).

So I'd lean toward the **near** search.

**Comment by shua123** [comment]
We've implemented search near for city names and zip codes. Issue #61 is also basically a dup of this so closing this one.

**Comment by versatilehuman** [comment]
@shua123 I'm having trouble with this. Municipality searches zoom in a little for a split second, then the map reloads. Zip codes aren't impacting the search at all. Chrome 51.0.2704.84 m (64-bit), Windows 7.

**Comment by versatilehuman** [comment]
@shua123 Ignore deleted comment. Forgot this was only implemented on the list side, should have checked the open issue.
