### ISSUE TITLE
"A" testers found two search boxes confusing

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#50]
During the recent CUTGroup test, we had two versions of the beta site, and "A" testers received a version with two search boxes (one for activities/amenities, and the other for location search). This was confusing to some and we saw instances of testers typing a search query in the wrong search box.

Recommendation is to move forward with this version that "B" testers used: http://fpcc-staging.smartchicagoapps.org/index-select2_v3.html

**Comment by shua123** [comment]
We decided to move forward with the 1 search box for now.
