### ISSUE TITLE
More clarity on trail type differences

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#51]
During CUTGroup testing, a tester pointed out two different trails and did not understand why they were listed as different types. The example was "Caldwell Woods" there is a "black paved" and a "blue paved" example with exactly the same activities listed. Same with "brown unpaved" and "blue unpaved."

A few questions:
- What distinguishes between these trails? 
- If they are different, how can we make it clearer that these are two different trail types?
- Could we only show the trails that are relevant to that entry type? For Caldwell Woods, there is only 1 trail associated with this location.

<img width="371" alt="screen shot 2016-03-11 at 1 41 06 pm" src="https://cloud.githubusercontent.com/assets/5550969/13713507/ef72a5ae-e78e-11e5-90c4-6e2d72317cec.png">

**Comment by shua123** [comment]
> What distinguishes between these trails?
The colors act as the names of different trails (or trail segments?) within the greater North Branch trail system. Is that correct @versatilehuman @glw ?

@smarziano I am confused about this question. I am not sure what you mean by entry type.
> Could we only show the trails that are relevant to that entry type? For Caldwell Woods, there is only 1 trail associated with this location.

**Comment by smarziano** [comment]
For clarification: If Caldwell Woods is the location result we choose and we only see a red paved trail on the map, do we need to list all of the different trail types in the detail panel?

**Comment by versatilehuman** [comment]
@shua123 Correct re: naming trail segments

@smarziano The thinking was we wanted to include the entire trail system that the location result has access to. Some users may want to plan a trip that includes multiple segments: 

> Start at Caldwell Woods on the Red Paved Trail then turn around on the Black Paved Trail loop, then ride back down the Red Paved Trail to Caldwell Woods. 

So for those people it's important to have that information for the whole system to see where it connects. If it just shows the Red Paved Trail, they wouldn't know that they could actually continue all the way to the Botanic Garden. They are color coded this way because that's what the wayfinding signage on the ground shows.

Let me know if that isn't clear. We can definitely walk through this at the meeting.

**Comment by shua123** [comment]
Naming may change some with trail data changes but we should make it clearer that the color is a name and something that would be seen on the ground.

**Comment by versatilehuman** [comment]
Will think more about this. What we discussed:

**Short term:** Should implement reordering by distance (longest first) and type (group paved and unpaved).

**Long term:** List the primary trail segment that the user can access from that location, then a note that says something like, "with access to" and list the rest of the segments.

Example: 

North Branch Trail System
[description]
Black Paved Trail
_with access to_
Red Paved Trail
Blue Paved Trail
Yellow Unpaved Trail
Brown Unpaved Trail

**Comment by shua123** [comment]
The panel now orders them in decreasing distance (longest first). It does not separate paved and unpaved.

**Comment by shua123** [comment]
"with access to" functionality added with commit https://github.com/smartchicago/trailsy/commit/90305284fb9de360bad5be9a62a99a6d655f75fd

**Comment by versatilehuman** [comment]
Awesome! I'll provide styling, need to add logic to prevent this:

![image](https://cloud.githubusercontent.com/assets/7032169/15614109/7f3891d6-23fc-11e6-9d59-c930e0a139eb.png)

**Comment by shua123** [comment]
Fixed! https://github.com/smartchicago/trailsy/commit/76acb20cb12c72e035b7469e75678d9a157ca00a

**Comment by versatilehuman** [comment]
@shua123 Implemented and styled. Close and keep an eye on next round of user testing?

![image](https://cloud.githubusercontent.com/assets/7032169/16425220/262218d8-3d29-11e6-92d8-18156138ebed.png)
