### ISSUE TITLE
Handling location results with the same name

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#52]
During our CUTGroup test, we asked testers to search for "Busse Forest" and multiple results came up. Testers were not sure which result to choose and did not understand why there were multiple results.

When looking more closely at the test results I will see if any testers added an additional search filter (like Busse Forest + Hiking) to make a better choice.

@shua123 I added this an issue because I don't know if there are other plans to better handle these locations that share the same name.

**Comment by versatilehuman** [comment]
There are quite a few areas that have multiple directional entrances (example: Miller Meadow-North, Miller Meadow-South). But it's usually two or three. Busse is just a beast. Maybe something like this? Where clicking on the general Busse Woods zooms you to the general location?

![image](https://cloud.githubusercontent.com/assets/7032169/13717945/dc1dc558-e7aa-11e5-8ca3-c086519994b2.png)

This could get really messy though for the user and for us on the data side. Need to think about this more.

**Comment by versatilehuman** [comment]
With addition of better pan/zoom (#56) and alt names (#84) this is better. The indented list above is not an elegant solution and I'm not sure there's a web map solution to what is really a naming of physical places problem. Showing all the entrances helps a potential visitor realize that there are multiple places to go at Busse Woods--and further investigation is needed (browsing, extra search term) to choose the right one for them.

@shua123 I'd say drop this as a potential enhancement. Thoughts?

**Comment by shua123** [comment]
Yeah I think dropping it is okay.
