### ISSUE TITLE
Additional information about preserves

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#54]
From my first review of CUTGroup test data here are some pieces of additional information that I heard from testers:
- rules of the Forest Preserves/permit information
- parking location (specifically on the map with icons)
- restroom locations

I will continue to add to this list as I review test results.

**Comment by versatilehuman** [comment]
@smarziano Parking/restroom locations will definitely be on there. 

Unfortunately our permit system doesn't allow for unique URLs to specific locations, so we can't include a "buy a permit" link -- which would be ideal. Maybe just a general link for rules and permit information?

**Comment by smarziano** [comment]
@versatilehuman Great re: parking/restroom locations!

I think a simple "buy a permit" link would do well at the bottom under "More Information." Or maybe if there is a specific activity that generally requires a permit (picnics come to mind) to show the link associated with that activity? It might be unnecessarily complicated to add that logic though.

**Comment by versatilehuman** [comment]
Rules/permit info added (#102). We decided against a parking icon on the map to reduce clutter--we adding parking lot outlines to the basemap for all preserves and parking will always be indicated in the panel. Restroom locations is still a to-do.
- [ ] rules of the Forest Preserves/permit information
- [ ] parking location (specifically on the map with icons)
- [ ] restroom locations

**Comment by versatilehuman** [comment]
Closing -- restroom locations has it's own issue #113
