### ISSUE TITLE
More information on activities and amenities

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#55]
During our CUTgroup test, we heard questions about the activities/amenities a preserve offers. One example is that a tester was interested in finding a place to rent a canoe. She searched for "Canoe" and saw that her only option was "canoe landing." She then wondered if a canoe landing can also rent canoes or if she has to bring her own. She was not sure, and then thought she might want to look at "Boat rentals" but did not know if boat rentals would have canoes.

**Comment by versatilehuman** [comment]
@smarziano We need to try to come up with a list of alternative names for activities and amenities that help this situation. One of my testers searched "run" or "running," which will be a common query, and came up empty. So the official amenity is hiking, but that should also trigger for "run," "jog," etc. Similar issue when someone searched "kayak."

**Comment by versatilehuman** [comment]
Covered in enhanced search and POI descriptions (example: POIs with boat rentals/launches indicate what boats are allowed. Provides link to more info about boat rentals).
