### ISSUE TITLE
Zoom and Pan guidelines

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#56]
This issue is to try to start documenting the various cases where we want to zoom and/or pan the map.As we define them, I will update this comment. I have listed some scenarios but there might be additional versions of these based on current zoom level or desktop vs mobile.

| Scenario | Zoom | Pan/centering |
| --- | --- | --- |
| User clicks on entrance in Results List | ? | ? |
| User clicks on Trail System in Results List | ? | ? |
| User clicks on entrance point on map | ? | ? |
| User clicks on activity on map | ? | ? |
| User clicks on trail segment on map | ? | ? |
| Clicking on activity icon in detail panel (Issue #29) | ? | ? |

@versatilehuman We talked about this some on Monday. Do you have notes on these + other scenarios?

**Comment by shua123** [comment]
@smarziano I think you had thoughts on this too...

**Comment by versatilehuman** [comment]
My thoughts based on Monday's conversation, but would be helpful to test this eventually (especially on mobile) and I'm interested in what others think. And not sure on how fine-tuned we can get for some of these.

Scenario | Zoom | Pan/centering
------------ | ------------- | ----------------
User clicks on entrance in Results List | * | Yes
User clicks on Trail System in Results List | * | Yes
User clicks on entrance point on map | ** | Yes
User clicks on activity on map | No | ***
User clicks on trail segment on map | No | No
Clicking on activity icon in detail panel (Issue #29) | ** | Yes
NEW: User executes a search | **** | ****
NEW: User clicks "Back to search" | **** | ****

*Zoom to level where all activities (for that entrance) or all parts of trail are on screen
**Only zoom if they are not already zoomed in far enough to display all activities; zoom to activity level only.
***Pan only if activity is outside of the currently activated entrance point (i.e. it's greyed out; let me know if that makes sense). Would pan to associated entrance point.
****Zoom/pan to fit all search results on map (I think this will help take care of Busse Woods situations)

**Comment by shua123** [comment]
> 2. Only zoom if they are not already zoomed in far enough to display all activities; zoom to activity level only.
@versatilehuman Can you please clarify what you mean by this one.

**Comment by shua123** [comment]
Scenario | Zoom | Pan/centering | Implemented
------------ | ------------- | ---------------- | ---------------
User clicks on entrance in Results List | 1 | Yes | Yes, https://github.com/smartchicago/trailsy/commit/882659179bda5ba0c2eaa39b46d9ef7d195e6fe1
User clicks on Trail System in Results List | 1 | Yes | Yes, https://github.com/smartchicago/trailsy/commit/882659179bda5ba0c2eaa39b46d9ef7d195e6fe1
User clicks on entrance point on map | 2 | Yes | Yes, https://github.com/smartchicago/trailsy/commit/b04fcfe7492db8d6724dc21e59ecf21b39c79133
User clicks on activity on map | No | 3 | Yes, https://github.com/smartchicago/trailsy/commit/b89efef0a953daca4e57ece42746ecc0d64051ea
User clicks on trail segment on map | No | No | Yes
Clicking on activity icon in detail panel (Issue #29) | 2 | Yes | No
NEW: User executes a search | 4 | 4 | Yes
NEW: User clicks "Back to search" | 4 | 4 | No

1. Zoom to level where all activities (for that entrance) or all parts of trail are on screen
2. Only zoom if they are not already zoomed in far enough to display all activities; zoom to activity level only.
3. Pan only if activity is outside of the currently activated entrance point (i.e. it's greyed out; let me know if that makes sense). Would pan to associated entrance point.
4. Zoom/pan to fit all search results on map (I think this will help take care of Busse Woods situations)

**Comment by versatilehuman** [comment]
@shua123 Sorry missed your comment. Current functionality is what I was trying to express.
