### ISSUE TITLE
Create Unique URLs

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#6]
Create unique urls so users can share or save. How would these work?

**Comment by shua123** [comment]
An initial pass at this is active as of https://github.com/smartchicago/trailsy/commit/d445dbcec31281ad887f929c05bffe70d1e537bf for trails/pois. It is not active for search yet.

**Comment by shua123** [comment]
Some to-do's:
- [ ] Remove from URL when detail panel is closed
- [ ] Add search string to URL
- [ ] Finalize what url will contain (currently id-name)

**Comment by shua123** [comment]
Okay, this is working decently right now for search and detail panel info. It can't handle populating both search and an open detail panel at the same time through the url cause things get funky but that can be added later.

**Comment by versatilehuman** [comment]
Looking good--let's keep the same structure until after QA (we are including URLs for reference). 

Trail URLs aren't working for me:

http://fpcc-staging.smartchicagoapps.org/#/?trail=Des+Plaines+Trail+System

![image](https://cloud.githubusercontent.com/assets/7032169/16663704/bc419be8-4442-11e6-9c7c-7acc3384b4e5.png)

**Comment by shua123** [comment]
Trail URLs should be working now...

**Comment by versatilehuman** [comment]
@shua123 I think id-name works, any reason not to approach this way?

**Comment by versatilehuman** [comment]
Site hangs up when a wrong URL is entered, can we have in forward to home/set a timeout?

Example:
http://smartchicago.github.io/trailsy/#/?poi=33212

![image](https://cloud.githubusercontent.com/assets/7032169/19663918/e36009a0-9a03-11e6-9fe7-ddbc2bf1b3ba.png)

**Comment by shua123** [comment]
This should now be fixed. I have it checking if it is a valid poi/trail first before taking any action.

**Comment by shua123** [comment]
Cal-Sag linking is not working for both a search url and a trail url.
