### ISSUE TITLE
Add zip code/municipalities to search

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#61]
@shua123 We should discuss how best to implement this.

**Comment by shua123** [comment]
An initial implementation of this is at https://github.com/smartchicago/trailsy/commit/d445dbcec31281ad887f929c05bffe70d1e537bf using zip/muni+latlng json files.

**Comment by shua123** [comment]
Plan:
Changes to make: 
- [ ] Remove 'Golf' from municipal zip code json
- [ ] Don't use municipality in search filtering. Always pan+sort if muni match

**Comment by shua123** [comment]
updates are implemented. It is not currently panning or zooming due to zip/muni. It just recalculates distance and reorders the list. 

Example:

Search Box | results list | map
----------------|----------------|-----------
"60625" | re-sorts with distance from 60625 | nothing
"60625 hiking" | shows hiking matches & re-sorts with distance from 60625 | pans and zooms to "hiking" match as outlined in #56 

We need to decide if & how zip/muni affects pan + zoom.

**Comment by shua123** [comment]
@versatilehuman any thoughts on my last comment about pan + zoom?

**Comment by versatilehuman** [comment]
@shua123 I think we pan and zoom to muni/zip if that's the only match. Those are most likely people trying to orient themselves, so we'd want to get them to their starting point.

Zoom level two steps closer than initial? I would say that level to start and see if it's disorienting. Municipalities on the outskirts and other counties may not have any preserves in view -- any way to combat that?

**Comment by shua123** [comment]
@versatilehuman thoughts on how it is now?

I think I am going to end up recalculating the lat/long for at least municipalities. I noticed Elmwood Park is wrong with the current data.

**Comment by versatilehuman** [comment]
@shua123 Zoom/pan is working for me on the first municipality search, but if I clear the search and enter a new municipality, it's only shuffling the results, no zoom/pan.

**Comment by shua123** [comment]
@versatilehuman I fixed the issue where pan/zoom was only working on the first zip/muni search.

**Comment by versatilehuman** [comment]
Zips seem to work (I found one that was missing from the data 60010 -- 42.123128, -88.139128). 

Municipality search from home (http://fpcc-staging.smartchicagoapps.org/):
map flashes to the north side of Cook County, maybe centering at Beck Lake, (regardless of term) for a second, then clears the search box and reverts map back to starting position. List disappears, then reappears at starting position.

Municipality search from page (http://fpcc-staging.smartchicagoapps.org/?#/?poi=108-Poplar+Creek+Equestrian+Parking) does nothing--no changes.

**Comment by shua123** [comment]
@versatilehuman I am having trouble replicating these municipality issues.

**Comment by versatilehuman** [comment]
@shua123 It's strange, cleared cache multiple times. Working for Jim, same browser and windows version. I'll check again tomorrow.

**Comment by versatilehuman** [comment]
@shua123 figured it out... it's capitalization.

"glenview" works, but "Glenview" doesn't.

**Comment by shua123** [comment]
ahh, yeah. That is fixed now.

**Comment by versatilehuman** [comment]
This seems to be working as intended... closing.

**Comment by versatilehuman** [comment]
@shua123 Forgot about this missing zip: 
60010 | 42.123128, -88.139128
