### ISSUE TITLE
Add alerts and other details to detail panel

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#62]
Add alerts and other features to detail panel based on Ryan's 4/13 email.
- [x] Alerts (for now)
- [x] “Special” description (call out for information on boat rentals, dog parks, etc.)
- [x] Hours
- [x] Phone
- [x] Featured photo

**Comment by versatilehuman** [comment]
Will fix alert CSS with the new tooltip CSS I'll send this week.

**Comment by shua123** [comment]
@versatilehuman on http://fpdcc.net/svg-test/panel-test.html you have the alerts block twice in the detail panel. Are these meant to be repeating the same alerts or is the 2nd block supposed to be alerts specific to the trail system?

**Comment by versatilehuman** [comment]
@shua123 One is POI specific and one is trail specific.

**Comment by versatilehuman** [comment]
@shua123 Featured photos no longer showing up, was photo_link column no longer in poi_desc data?

Looks fine in code:
https://github.com/smartchicago/trailsy/blob/gh-pages/js/trailhead.js#L2236

**Comment by shua123** [comment]
Looks like I didn't include it in the updated json api on the server.

**Comment by shua123** [comment]
Photos should be back on pois now. https://github.com/smartchicago/trailsyserver/commit/45f645136f655fd845d630ec9655519b7a2b432a

**Comment by versatilehuman** [comment]
Need to resolve any remaining caching issues.

**Comment by shua123** [comment]
Reduced cache expiration

**Comment by shua123** [comment]
Can we close this @versatilehuman ?

**Comment by versatilehuman** [comment]
Yes
