### ISSUE TITLE
Investigate switching away from select2.js

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#63]
With Select2.js if a user types and then clicks outside of the box, select2 does not save that text. There is a "selectOnClose: true" setting but with that setting it is impossible to close the drop down box without selecting one of the features.

Possibly switch to http://selectize.github.io/selectize.js/. Selectize createOnBlur option appears to function closer to how we want- "selecting"/saving the text but not auto-choosing something in the drop down. http://jsfiddle.net/q6tmyeb8/
Also check https://arendjr.github.io/selectivity/

**Comment by versatilehuman** [comment]
@shua123 Do we want to sit down and think about revamping search comprehensively (including #61).  How to weigh text matches found in different places (I eliminated many location references that throw off search in the updated descriptions).

**Comment by shua123** [comment]
Testing out selectize with other search changes in https://github.com/smartchicago/trailsy/tree/selectize2

**Comment by shua123** [comment]
We did this! We've switched to selectize2 for now. We've also sat down and thought about revamping search.
