### ISSUE TITLE
POI description persists on new selected location

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#64]
When moving from a location with a description to one without, the description for the first location persists in the panel:

![image](https://cloud.githubusercontent.com/assets/7032169/14646560/8a9d0f20-061f-11e6-8cde-d6789895846f.png)

This continues with each location selected until selecting another location with a description.

**Comment by shua123** [comment]
This should be better now with https://github.com/smartchicago/trailsy/commit/ba55ef05258a6f447a156ad9dacc0153f873424a

**Comment by shua123** [comment]
I am closing this for now. @versatilehuman please reopen if you still see this happening.
