### ISSUE TITLE
Remove space between SVG icon and label in panel

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#65]
Some of these have a space between `</svg>` and `<span class="fpccAmenityTitle">`. Need to remove to display properly (this is my fault):

`<svg class="icon icon-hiking"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="icons/defs.svg#icon-hiking"></use></svg> <span class="fpccAmenityTitle">Hiking</span>`

should be:

`<svg class="icon icon-hiking"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="icons/defs.svg#icon-hiking"></use></svg><span class="fpccAmenityTitle">Hiking</span>`

**Comment by shua123** [comment]
I think I got them all. Let me know if you still find any.

**Comment by shua123** [comment]
Closing this for now. @versatilehuman please reopen if you find any more.
