### ISSUE TITLE
Incorrect address display

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#66]
Right now the estimated address is displayed in the panel. But we need logic that says:

> IF official address exists, display official address, ELSE display "City, State ZIP."

That way we are only publishing official addresses. The directions use lat/long, so I don't think we need to use the estimated addresses at all. @shua123 I can dig through the columns to see which we need to use if you want, just need a copy of the table it's coming from (poi_info?)

**Comment by shua123** [comment]
I have been pulling this from the poi_info table. 

There is an 'addr' field that I am using. It is the only field I am using because it has the city and zip in it a lot of the times but it is inconsistent. There are separate zip, zipmuni, and municipality fields.  Take a look at the table and see what you and @glw want to do with it.

**Comment by versatilehuman** [comment]
Got it. Talked to @glw and will create a new address column for web display.

**Comment by versatilehuman** [comment]
This is done in the next data update. Guidance from email: 

**Addresses**
I added intersection guidance or an actual address for each location with an entrance (**web_street_addr** in **poi_info**). I added municipality/zip code for all POIs (**web_muni_addr** in **poi_info**)



**Address Search**
For search, street names will be in **web_street_addr** in **poi_info**. We don’t want to search **web_muni_addr** for address search (i.e. matching street names).



**Address Display**
I removed entrance ID associations (**parking_entrance_id** in **poi_info**) for locations that don’t have entrances. I moved that entrance ID (when appropriate) to a new column called **parking_connection_id**. Hopefully we can add a link that says “View closest parking area” that links to the URL/pans to that parking entrance—see (3) below. Let me know if that makes sense. I don’t think it’s critical for July 15, but something that will be valuable when we can include it. 

Build addresses like this:

(1) IF [**web_street_addr** from **poi_info**] exists:

```
<span class="fpccLabel fpccBlock">Entrance</span>
<span class="fpccEntranceAddress">[web_street_addr from poi_info]</span>
<span class="fpccEntranceZip">[web_muni_addr from poi_info]</span>
```

(2) IF [**web_street_addr** from **poi_info**] DOES NOT exist:

```
<span class="fpccLabel fpccBlock">Location</span>
<span class="fpccEntranceZip">[web_muni_addr from poi_info]</span>
```

(3) IF [**web_street_addr** from **poi_info**] DOES NOT exist AND [**parking_connection_id** from **poi_info**] exists:

```
<span class="fpccLabel fpccBlock">Location</span>
<span class="fpccEntranceZip">[web_muni_addr from poi_info]</span>
<span class="fpccCloseParking"><href=”[link to location at parking_connection_id]”>View closest parking area</a></span>
```

**Comment by shua123** [comment]
Added address line back into search: https://github.com/smartchicago/trailsy/commit/df1732d77ceebf26ce2ebdd51ffb5314ceff44ec

**Comment by shua123** [comment]
Okay, (1) and (2) are done.

(3) needs some more work.

**Comment by shua123** [comment]
@versatilehuman For (3), can you explain what you mean by 
> [link to location at parking_connection_id]

**Comment by versatilehuman** [comment]
@shua123 It would plug in the URL from whatever poi_info_ID was included in the parking_connection_id column.

**Comment by shua123** [comment]
It looks like parking_connection_id is a parking_info_id not poi_info_id or parking_entrance_id.

So I need to take the parking_connection_id, check if any poi_infos are associated with that parking_info_id. If there is a poi_info associated with the parking_info_id, have the link `<span class="fpccCloseParking"><href=”[link to location at parking_connection_id]”>View closest parking area</a></span>` open up the detail panel for and pan/zoom to that poi?

**Comment by versatilehuman** [comment]
@shua123 Sorry, yes it would match the parking_entrance_id, then proceed as you outlined.

**Comment by shua123** [comment]
"View closest parking area" added to poi detail panel display where parking_connection_id exists. Updated on gh-pages version.

**Comment by versatilehuman** [comment]
Looks good. Only issue I see is browser "back" functionality doesn't work after clicking link. Example:

http://smartchicago.github.io/trailsy/#/?poi=2-Cap+Sauers+Holding+Nature+Preserve

After click, stuck at Teason's.

**Comment by shua123** [comment]
Back should work okay now. https://github.com/smartchicago/trailsy/commit/5bb5a8e0119ee32beea9e68fb31324a4d88edb9b

**Comment by shua123** [comment]
Logic issue with close parking: If the close parking poi has been filtered out with search, there won't be anything there.

Example: Search "cap sauers". There will be one result. Click on it to go to Cap+Sauers+Holding+Nature+Preserve. Now if you click on the View closest parking link, the map will go to Teasons Woods but there is no sign icon since that POI had been filtered out by the search.
![image](https://cloud.githubusercontent.com/assets/1593537/23088963/c354e5a0-f547-11e6-81f9-51f75e59d9b6.png)

Thoughts?

**Comment by versatilehuman** [comment]
Good catch. Let me look at that column next week. I think we could add the closest parking area as an alt name so it shows up in search -- it should make sense for all these but I want to double check.

**Comment by versatilehuman** [comment]
All these make sense for an alt_name column, so I've updated and should be included in next data update.

**Comment by shua123** [comment]
Well that only really fixes it for name based searches. If you search for an amenity/activity that POI A has but Closest Parking Related POI B doesn't, it still is an issue.

**Comment by versatilehuman** [comment]
Hmmm...

I'm at a loss here. We definitely don't want locations without that amenity/activity showing up in search just for the benefit of this. The names works because there is an actual association.

Is there a way to add the POI when the link is clicked? BUT... Let's not make this a priority for now.

@shua123 You think launch with it as is (plus alt name update) or disable? If we launch with it, we can get an estimate on usage through analytics by tracking how many people came from the non-parking POI to the parking POI -- and see what kind of search they executed before that. If it's impacting a lot of people we can re-prioritize?
