### ISSUE TITLE
Entrance sign icon persists after zoom out or reset of search

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#67]
Previously selected entrance sign icon persists after zoom out or reset of search:

![image](https://cloud.githubusercontent.com/assets/7032169/14647270/8e6ae12e-0622-11e6-9099-deec7afb86ae.png)

If I select a location, then close it, then zoom out: sign persists.
If I select a location, then zoom out, then close it: resets to dot.

I'll add any other patterns I notice.

**Comment by shua123** [comment]
Thanks. I saw this one but hadn't made an issue for it.

**Comment by shua123** [comment]
How attached are you to the orange circles @versatilehuman ?

**Comment by versatilehuman** [comment]
Not even a little bit @shua123.

**Comment by shua123** [comment]
@versatilehuman I have removed the orange circles in favor of using the divicon icon-sign at all zoom levels with size adjustments based on zoom level (through adding & removing zoomlevel classes). https://github.com/smartchicago/trailsy/blob/c2663514c530a26796ad467375a7457eac8c8d7c/styles/css/newguts.css#L153

This change will solve this issue.

**Comment by shua123** [comment]
Closing this issue since it is solved through the removal of circles and :+1:
