### ISSUE TITLE
Trails cut-off when selecting location doesn't require zoom/pan

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#69]
When selecting an entrance at a zoom level that doesn't require a zoom/pan adjustment, trails cut off as if it was rendering them for a selection from a zoom level that would have required a zoom/pan adjustment (i.e. it renders the trails based on thinking the entrance is at a pre-determined point, but the point isn't).

![image](https://cloud.githubusercontent.com/assets/7032169/15297048/d45bc18a-1b5d-11e6-9155-e3fa34188bbb.png)

![image](https://cloud.githubusercontent.com/assets/7032169/15297051/d7e1fb4e-1b5d-11e6-9c69-b27dae20c95a.png)

**Comment by shua123** [comment]
Well that is weird. I wonder if I messed up something with styling logic for segments. I'll dig around.

![image](https://cloud.githubusercontent.com/assets/1593537/15299308/66d16ef6-1b69-11e6-8f5e-5daa5d10b3d9.png)

![image](https://cloud.githubusercontent.com/assets/1593537/15299323/7954a3ea-1b69-11e6-9e26-dfe6a5ce6913.png)

**Comment by shua123** [comment]
Hmm, it looks like its not re-centering properly. It reminds me of the issue we encountered before https://github.com/smartchicago/trailsy/issues/26#issuecomment-186016162 .

**Comment by shua123** [comment]
I might try killing the animation part of what we added ( #43 ) to see if the animation is causing this.

**Comment by versatilehuman** [comment]
Or maybe it's the extra padding to facilitate the highlighting?

**Comment by shua123** [comment]
I stepped through the changes/commits that led to this and found the issue (though I'm not sure why yet). Good news is that animation is possible. @versatilehuman fixed version is on staging.

**Comment by versatilehuman** [comment]
@shua123 Some version of this has returned on staging: 

![image](https://cloud.githubusercontent.com/assets/7032169/17001989/fc5d2804-4e8e-11e6-998b-f2a71d27b109.png)

**Comment by shua123** [comment]
Hmm, I switched Leaflet versions which may have caused something.

**Comment by versatilehuman** [comment]
This is happening too (not a big deal, still need to style these), if that helps:

![image](https://cloud.githubusercontent.com/assets/7032169/17002759/7f983a4e-4e92-11e6-9679-17ca96c64aa1.png)

**Comment by shua123** [comment]
It looks like the line thing is a Leaflet 1.0rc2 bug. I am going to keep an eye on it to see when they fix it. I'd like to not revert back to a .7x version of Leaflet if possible but I will if it doesn't get fixed soon.

**Comment by shua123** [comment]
Updated with a new version of leaflet that appears to fix this.
https://github.com/smartchicago/trailsy/commit/55cd5f154812543173dff20e5911d6d3007300f7
