### ISSUE TITLE
Activity Data: Display names on map for select types

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#7]
Display names on map for Activity types:
* Facilities
* Waterbodies
* Picnic groves

**Comment by shua123** [comment]
![image](https://cloud.githubusercontent.com/assets/1593537/13128978/868cb2ec-d59f-11e5-80e7-b862c3d661cd.png)

**Comment by shua123** [comment]
I believe this has been implemented. Will need to check with new data and refine.

**Comment by versatilehuman** [comment]
When we add picnic groves:
icon-picnic-grove
icon-picnic-grove-shelter

Something like "Grove 1"

**Comment by versatilehuman** [comment]
Discontinued.
