### ISSUE TITLE
POI Amenities search/filter

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#70]
Ryan updating boolean columns in poi_info table to cover all filters. 

Need to add tags (or whatever) for alt versions of filters. Example:

> A search for "running" triggers the hiking filter. 

Ryan will provide alt versions to Josh.

**Comment by shua123** [comment]
Version of this implemented based on @versatilehuman spreadsheet

**Comment by versatilehuman** [comment]
Looks good. How are the popular searches currently ordered? What's the easiest way to prioritize the order?

**Comment by shua123** [comment]
Popular searches are ordered manually at the moment. I plan to make that something better.

Let me know if you want to adjust the popular search order now for launch.

**Comment by versatilehuman** [comment]
@shua123 Here's the order for launch:

Hiking / Walking / Running
Biking
Nature Center
Camping
Picnic / Event Space
Volunteering
Dogs (with leash only)
Dog Park
Canoeing / Kayaking / Boating
Swimming
Cross-Country Skiing
Sledding

**Comment by shua123** [comment]
Reordered https://github.com/smartchicago/trailsy/commit/b1722aae9f0003f274e6e157541767dc5d41a79f

**Comment by versatilehuman** [comment]
@shua123 Looks like we lost the seasonality. If we can't dynamically add that right now, can you remove:
Swimming
Cross-Country Skiing
Sledding

**Comment by shua123** [comment]
Yeah its manual for now. I've hidden those three from the popular section.

**Comment by versatilehuman** [comment]
@shua123 Can you alpha-order the "Everything" -- these got tagged on the end: Swimming, Cross-Country Skiing, Sledding

**Comment by shua123** [comment]
Fixed on gh-pages.

**Comment by versatilehuman** [comment]
Looks good.
