### ISSUE TITLE
Add picnic grove data

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#72]
From Garret.

**Comment by shua123** [comment]
Picnic Groves added on staging

**Comment by versatilehuman** [comment]
Functionality is there. All the icons are **picnic grove**, not seeing any **picnic grove (with shelter)** -- is that an issue with the data? How is the naming working?

**Comment by shua123** [comment]
It was an issue with how I imported the data and will be fixed in my next update.

**Comment by shua123** [comment]
Updated on staging
