### ISSUE TITLE
Add menu to navigate to fpdcc.com, about page, feedback

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#75]
- [x] About / Contact page
- [x] Give feedback page
- [x] Functional on mobile

**Comment by shua123** [comment]
Initial version added with https://github.com/smartchicago/trailsy/commit/2e3e269741f05433fd63fdd01e2339e313e3dd11 .
About & feedback links go nowhere at the moment.

**Comment by versatilehuman** [comment]
@shua123 The feedback form upload is failing and I'm reluctant to spend time troubleshooting if we can use Wufoo. Can you create something similar to the existing one? 

https://script.google.com/macros/s/AKfycby6fEFxi92eh152A7x4iPy6tRjevGbpRgCUTTaKNMBfwqdDHVvZ/exec

**Comment by versatilehuman** [comment]
@shua123 CSS is update on gh-pages to have the mobile menu work. JS is appending "hide" class on first click though...

Also removed a redundant menu for index.html.

**Comment by versatilehuman** [comment]
@shua123 Would also be nice to eventually have the menu close when the user clicks or touches off the menu (both desktop and mobile). Have a feeling some users will struggle with closing menu by touching hamburger icon again. And will have trouble getting off the About page because it obscures the X icon:

![image](https://cloud.githubusercontent.com/assets/7032169/23368317/08ad47cc-fcd3-11e6-8fc8-4496dc449417.png)

**Comment by shua123** [comment]
Close menu when clicking outside of menu list: https://github.com/smartchicago/trailsy/commit/1f8fa80bb830b40e114ccb2cd84c68879e049256

**Comment by versatilehuman** [comment]
@shua123 feedback from looks good on dev
