### ISSUE TITLE
After search, filter out trails on map

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#77]
Can we filter out trails on the map to match the results list? (like we do with POIs)

Only issue I see implementing this is not wanting to hide trail systems that connect to a search result. Suggestions on how to accomplish that, @shua123? Low-tech way would be to have trail connections listed in description.

![image](https://cloud.githubusercontent.com/assets/7032169/15912250/c3a98032-2d98-11e6-9719-ddc58f02557a.png)

**Comment by shua123** [comment]
Trails are supposed to be filtered. I'll have to check what is happening

**Comment by shua123** [comment]
Fixed.
