### ISSUE TITLE
Based on filter show/hide trails from list and/or map

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#81]
>  Realized after doing a search for snowmobiling that having trails show up in the search results for some activities will be problematic. Most are just excluded from the list (because they wouldn’t make sense) but still included on the map (for discoverability). Four are excluded from both because we don’t want there to be any confusion about whether those activities are allowed on trails.

**Comment by shua123** [comment]
A hacky version of this is implemented. It works but should probably be redone later.

**Comment by versatilehuman** [comment]
Looks good.

**Comment by versatilehuman** [comment]
Seeing trails in searches for snowmobile again:

![image](https://cloud.githubusercontent.com/assets/7032169/17300409/efd6e672-57d7-11e6-90f6-340d93446781.png)
