### ISSUE TITLE
Determine correct icon for each activity point on map

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#82]
atype = field name in the activities table that contains the type of activity. 
Map Icon Name = icon name as it appears in defs.svg file.
@versatilehuman Please confirm and help me fill in the blanks.

| atype | Map Icon Name |
| --- | --- |
| bicycle lot | shouldn't have an icon on the map |
| bicycle rental | icon-bike-rental |
| birding hotspot | shouldn't have an icon on the map |
| boat launch | icon-boat-launch |
| boat rental | icon-boat-rental |
| boating center | icon-boat-rental |
| canoe landing | icon-canoe-landing |
| dog park | icon-off-leash-dog-area |
| equestrian center | icon-facility |
| equestrian parking | shouldn't have an icon on the map |
| frisbee golf | icon-disc-golf |
| golf course | icon-golf-course-driving-range |
| golf driving range | icon-golf-course-driving-range |
| model airplane flying field | icon-model-airplane |
| pavilion | icon-facility |
| recreational waterbody | icon-waterbody |
| scenic | shouldn't have an icon on the map |
| sledding | icon-sledding |
| snowmobiling | icon-snowmobiling |
| special activity | icon-facility |
| trailhead | icon-trail-marker |
| volunteer center | icon-facility |
| warming shelter | icon-facility |
| welcome center | icon-facility |
| campground | icon-camp |
| zipline | icon-zip-line |
| drone | icon-drone |
| nature center | icon-nature-center |
| headquarters | icon-facility |
| recreation center | icon-zip-line |

**Comment by versatilehuman** [comment]
@shua123 Updated. Where are there "special activity" occurrences? 

Campgrounds should have an icon and don't (assume they are missing from activity data).

Zip line is missing on map and in panel (Bemis Woods South, in poi_info table has "yes" for "zip_line" column, assume missing from activity data so not on map).

**Comment by shua123** [comment]
Campgrounds and zip lines are missing from activity data so not on map. I've fixed the rest.

**Comment by versatilehuman** [comment]
Great, I'll review as I QA

**Comment by versatilehuman** [comment]
@shua123 Added three more to end

**Comment by shua123** [comment]
I added drone, nature center and headquarters to the activity type icons. I don't think we have any activities with those types in the data on there right now though.

**Comment by versatilehuman** [comment]
Review after data update.

**Comment by versatilehuman** [comment]
Mathew Bieszczat Volunteer Resource Center (volunteer center activity?) should use icon-facility on map https://fpcc-staging.smartchicagoapps.org/#/?poi=397-Mathew+Bieszczat+Volunteer+Resource+Center

**Comment by versatilehuman** [comment]
@shua123 On map zip line activity will have "recreation center" as atype in new data from Garret. This should still use icon-zip-line. Added to the end.

**Comment by versatilehuman** [comment]
@shua123  IGNORE last comment, Was looking for something and updated in trailhead.js: https://github.com/smartchicago/trailsy/blob/gh-pages/js/trailhead.js#L1201

**Comment by versatilehuman** [comment]
Updated volunteer center icon: https://github.com/smartchicago/trailsy/blob/gh-pages/js/trailhead.js#L1187

Should be good to go.

**Comment by versatilehuman** [comment]
@shua123 is recreation center activity type include on the server?

**Comment by versatilehuman** [comment]
Need to design and check implimentation of recreation_center #131 and can close
