### ISSUE TITLE
Entrance Detail Panel: Only display "No Fishing" Icon where it makes sense

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#9]
Right now the No Fishing Icon is showing up on all entrance points regardless of if there is any water there. Change the logic to only show No Fishing if there is a waterbody.

**Comment by shua123** [comment]
I am not sure what field to use to determine if there is a waterbody.

**Comment by versatilehuman** [comment]
There should (eventually) be a waterbody data set from GIS.

**Comment by glw** [comment]
Hmm, thats odd because "No Fishing" points have not been added to the data yet. Is it showing all points where fishing = 0 as being no fishing?

**Comment by shua123** [comment]
Yeah, that is just the initial way I matched up the icons and attributes.

**Comment by versatilehuman** [comment]
Added no fishing to boolean in poi_info.
