### ISSUE TITLE
Entrances showing up at centroid point

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#90]
No longer showing up at actual entrances. New after adding alt names for #84? 

![image](https://cloud.githubusercontent.com/assets/7032169/16919021/b5a6ecaa-4ccd-11e6-8b3a-0e2e8cb8b23a.png)

**Comment by versatilehuman** [comment]
Realized not getting any non-entrance icons on map either.

**Comment by shua123** [comment]
This should be better now
