### ISSUE TITLE
Trails not showing up in search... for searches of trail names

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#91]
A search for "biking" will surface North Branch Trail as a result.

A search for "North Branch Trail" does not. 

Did we leave trails out of the name match?

**Comment by shua123** [comment]
No, this is a stupid bug from something I did related to the show/don't show trails in detail panel settings. I noticed it a couple days ago but forgot to create an issue. It will be fixed soon.

**Comment by versatilehuman** [comment]
This ever get figured out?

**Comment by shua123** [comment]
Fixed on gh-pages. I thought this same problem was mentioned in another Issue but I can't find it now.

**Comment by versatilehuman** [comment]
Couldn't find it either.
