### ISSUE TITLE
Name match search enhancement

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#92]
Configure for words out of order?

Doesn't work:
http://fpcc.smartchicagoapps.org/#/?search=busse+elk
http://fpcc.smartchicagoapps.org/#/?search=elk+busse

Works:
http://fpcc.smartchicagoapps.org/#/?search=busse+forest+elk
http://fpcc.smartchicagoapps.org/#/?search=elk

**Comment by shua123** [comment]
Put together a version of this on staging for name matches only.

**Comment by versatilehuman** [comment]
Looks good!
