### ISSUE TITLE
Extra (related) amenities in panel 

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#93]
Maybe related to search functions?

Allison Woods only has a canoe landing, but rental and boat launch are included:
![image](https://cloud.githubusercontent.com/assets/7032169/17004477/c6917a84-4e9a-11e6-8c8f-533b6b24a927.png)
http://fpcc-staging.smartchicagoapps.org/#/?poi=337-Allison+Woods
"boating" search would pull up anything with canoe landing, boat launch or boat rental.

Arrowhead Lake only has sheltered picnic grove, but regular picnic grove is also included:
![image](https://cloud.githubusercontent.com/assets/7032169/17004498/e3b03dee-4e9a-11e6-8978-f9d3d50a11e2.png)
http://fpcc-staging.smartchicagoapps.org/#/?poi=128-Arrowhead+Lake
"picnic" search would pull up anything with picnic grove or sheltered picnic grove.

**Comment by shua123** [comment]
Related Trailsyserver commit: https://github.com/smartchicago/trailsyserver/commit/88eb7581a484bc34d300c1f11657981434709314

This should generally be fixed. In the case of Arrowhead Lake, both "picnic_grove" and "shelter" fields are 1 for that poi in the copy of the data I have.

**Comment by versatilehuman** [comment]
Good for water related stuff. Let's wait to close until the data update--there was a lot of erroneous picnic grove/shelter data and I want to be 100% sure.

**Comment by versatilehuman** [comment]
Will detect on final QA, closing for now.
