### ISSUE TITLE
Schema update: fix pavilion spelling

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#95]
> Pavilion was spelled wrong (had two Ls) in poi_info table, but is now correct in data -- should be updated on your end
> 
> pavilion | icon-facility (pavilion was spelled wrong in activities table (had two Ls), but is now correct in data, so update on your end

**Comment by shua123** [comment]
Waiting for updated data that contains this correction before updating server and trailsy.

**Comment by shua123** [comment]
I think this should be good now. @versatilehuman please have a look.

**Comment by versatilehuman** [comment]
looks good.
