### ISSUE TITLE
QA Panel Updates

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#96]
- [x] Remove ecological management (ecological) from panel completely
- [x] IF “public_building=1” display:
  Icon: icon-facility
  Text: Public Building
- [x] IF “no_parking=1” display:
  Icon: icon-no-parking
  Text: No Parking Lot
- [x] IF “no_parking=0” display:
  Icon: icon-parking
  Text: Parking Lot
- [x] IF “drone=1” display:
  Icon: icon-drone
  Text: Drone Flying Area
- [x] IF “driving_range=1” display:
  Icon: icon-golf-course-driving-range
  Text: Driving Range
- [x] IF “no_fishing=1” display:
  Icon: icon-no-fishing
  Text: No Fishing

**Comment by shua123** [comment]
Updated trailsy side. still need to update Trailsyserver side for some of these

**Comment by versatilehuman** [comment]
With latest data update, not seeing:
IF “public_building=1” display: Icon: icon-facility Text: Public Building
IF “driving_range=1” display: Icon: icon-golf-course-driving-range Text: Driving Range

**Comment by shua123** [comment]
Both of those were missing from the latest data update.

**Comment by versatilehuman** [comment]
Ok, I'll include in latest QA doc and make sure it gets in there.

**Comment by shua123** [comment]
public_building and driving_range fields added back on server(https://github.com/smartchicago/trailsyserver/commit/64c616bbc2f6803db61ee9a3aaf457c402841446). Waiting for new data with these fields.

**Comment by shua123** [comment]
public_building and driving_range are in the latest data. However, driving_range is 0 for all pois.
