### ISSUE TITLE
QA: Trail display issues

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#97]
- [x] Some trail_type=natural surface/primitive/stone trails showing up as solid on map and “paved” in panel
- [x] “Off FPDCC” segments no longer labeled

**Comment by shua123** [comment]
I made a change for the map to hopefully display those trails as dashed. @versatilehuman do you have an example of a trail showing up solid and paved in panel?

**Comment by versatilehuman** [comment]
I can't find one, in a couple system there is a paved trail and a natural surface/primitive/stone trail with the same color and I think my eye was drawn to the paved one in the panel as I went through. My mistake.

**Comment by versatilehuman** [comment]
@shua123 Found the "stone" rendering issue:
http://smartchicago.github.io/trailsy/#/?poi=372-Orland+Grassland+South

Stone surface should be dashed on map and allow bike, hike, ski & equestrian. Already dashed in panel.

**Comment by shua123** [comment]
Stone path css is fixed.
