### ISSUE TITLE
QA General Other

### ISSUE THREAD

**Issue by shua123** [smartchicago/trailsy#99]
- [x] Add conditional logic to remove PDF map buttons if none exist (example: http://fpcc.smartchicagoapps.org/#/?trail=Dan+Ryan+Trails)
- [x] Remove rec waterbody names on map (I think it will be cleaner to try to accomplish this on the base map)
- [x] Change page title to: Map: Forest Preserves of Cook County
- [x] Remove “read more” links after POI descriptions

**Comment by shua123** [comment]
Conditional logic for PDF map buttons has already been added.

**Comment by shua123** [comment]
All done

**Comment by versatilehuman** [comment]
@shua123 Can we update page title to:

Home (same as now): 
Map: Forest Preserves of Cook County

POI:
Map: POI Name | Forest Preserves of Cook County

Trail:
Map: Trail Name | Forest Preserves of Cook County

**Comment by shua123** [comment]
POI/Trail name is now added to page title on gh-pages

**Comment by versatilehuman** [comment]
Looks good

**Comment by versatilehuman** [comment]
@shua123 Page title is reflected in the browser tab, but not in the actual code, which is causing issues with Facebook sharing (#123)

![image](https://cloud.githubusercontent.com/assets/7032169/19328786/fb33893e-909a-11e6-8b98-6b2e270c6308.png)

![image](https://cloud.githubusercontent.com/assets/7032169/19328794/06f4fcd0-909b-11e6-85fc-5e1b3280da6b.png)

**Comment by versatilehuman** [comment]
See #123
